// flow-typed signature: a8fd7872dade2bf3a0cd91e9e446ecd0
// flow-typed version: <<STUB>>/@fortawesome/react-fontawesome_v^0.1.4/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/react-fontawesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/react-fontawesome' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fortawesome/react-fontawesome/index.es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fortawesome/react-fontawesome/index.es.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome/index.es'>;
}
declare module '@fortawesome/react-fontawesome/index' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome'>;
}
declare module '@fortawesome/react-fontawesome/index.js' {
  declare module.exports: $Exports<'@fortawesome/react-fontawesome'>;
}
