// flow-typed signature: ba787fec982c5212e93f461b566a350e
// flow-typed version: <<STUB>>/bugsnag-build-reporter_v^1.0.3/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bugsnag-build-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bugsnag-build-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bugsnag-build-reporter/bin/cli' {
  declare module.exports: any;
}

declare module 'bugsnag-build-reporter/lib/logger' {
  declare module.exports: any;
}

declare module 'bugsnag-build-reporter/lib/payload' {
  declare module.exports: any;
}

declare module 'bugsnag-build-reporter/lib/schema' {
  declare module.exports: any;
}

declare module 'bugsnag-build-reporter/lib/send' {
  declare module.exports: any;
}

declare module 'bugsnag-build-reporter/lib/source-control' {
  declare module.exports: any;
}

declare module 'bugsnag-build-reporter/lib/test/schema.test' {
  declare module.exports: any;
}

declare module 'bugsnag-build-reporter/lib/test/send.test' {
  declare module.exports: any;
}

declare module 'bugsnag-build-reporter/lib/test/source-control.test' {
  declare module.exports: any;
}

declare module 'bugsnag-build-reporter/lib/validate' {
  declare module.exports: any;
}

declare module 'bugsnag-build-reporter/lib/whoami' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bugsnag-build-reporter/bin/cli.js' {
  declare module.exports: $Exports<'bugsnag-build-reporter/bin/cli'>;
}
declare module 'bugsnag-build-reporter/index' {
  declare module.exports: $Exports<'bugsnag-build-reporter'>;
}
declare module 'bugsnag-build-reporter/index.js' {
  declare module.exports: $Exports<'bugsnag-build-reporter'>;
}
declare module 'bugsnag-build-reporter/lib/logger.js' {
  declare module.exports: $Exports<'bugsnag-build-reporter/lib/logger'>;
}
declare module 'bugsnag-build-reporter/lib/payload.js' {
  declare module.exports: $Exports<'bugsnag-build-reporter/lib/payload'>;
}
declare module 'bugsnag-build-reporter/lib/schema.js' {
  declare module.exports: $Exports<'bugsnag-build-reporter/lib/schema'>;
}
declare module 'bugsnag-build-reporter/lib/send.js' {
  declare module.exports: $Exports<'bugsnag-build-reporter/lib/send'>;
}
declare module 'bugsnag-build-reporter/lib/source-control.js' {
  declare module.exports: $Exports<'bugsnag-build-reporter/lib/source-control'>;
}
declare module 'bugsnag-build-reporter/lib/test/schema.test.js' {
  declare module.exports: $Exports<'bugsnag-build-reporter/lib/test/schema.test'>;
}
declare module 'bugsnag-build-reporter/lib/test/send.test.js' {
  declare module.exports: $Exports<'bugsnag-build-reporter/lib/test/send.test'>;
}
declare module 'bugsnag-build-reporter/lib/test/source-control.test.js' {
  declare module.exports: $Exports<'bugsnag-build-reporter/lib/test/source-control.test'>;
}
declare module 'bugsnag-build-reporter/lib/validate.js' {
  declare module.exports: $Exports<'bugsnag-build-reporter/lib/validate'>;
}
declare module 'bugsnag-build-reporter/lib/whoami.js' {
  declare module.exports: $Exports<'bugsnag-build-reporter/lib/whoami'>;
}
