// flow-typed signature: 618b61daae502e4b129d06ea97de0218
// flow-typed version: <<STUB>>/bugsnag-sourcemaps_v^1.3.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bugsnag-sourcemaps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bugsnag-sourcemaps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bugsnag-sourcemaps/cli' {
  declare module.exports: any;
}

declare module 'bugsnag-sourcemaps/lib/cleanup-temp-files' {
  declare module.exports: any;
}

declare module 'bugsnag-sourcemaps/lib/cli-logger' {
  declare module.exports: any;
}

declare module 'bugsnag-sourcemaps/lib/does-file-exist' {
  declare module.exports: any;
}

declare module 'bugsnag-sourcemaps/lib/get-app-version' {
  declare module.exports: any;
}

declare module 'bugsnag-sourcemaps/lib/options' {
  declare module.exports: any;
}

declare module 'bugsnag-sourcemaps/lib/prepare-request' {
  declare module.exports: any;
}

declare module 'bugsnag-sourcemaps/lib/read-file-json' {
  declare module.exports: any;
}

declare module 'bugsnag-sourcemaps/lib/request' {
  declare module.exports: any;
}

declare module 'bugsnag-sourcemaps/lib/strip-project-root' {
  declare module.exports: any;
}

declare module 'bugsnag-sourcemaps/lib/test/options.test' {
  declare module.exports: any;
}

declare module 'bugsnag-sourcemaps/lib/test/prepare-request.test' {
  declare module.exports: any;
}

declare module 'bugsnag-sourcemaps/lib/test/strip-project-root.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bugsnag-sourcemaps/cli.js' {
  declare module.exports: $Exports<'bugsnag-sourcemaps/cli'>;
}
declare module 'bugsnag-sourcemaps/index' {
  declare module.exports: $Exports<'bugsnag-sourcemaps'>;
}
declare module 'bugsnag-sourcemaps/index.js' {
  declare module.exports: $Exports<'bugsnag-sourcemaps'>;
}
declare module 'bugsnag-sourcemaps/lib/cleanup-temp-files.js' {
  declare module.exports: $Exports<'bugsnag-sourcemaps/lib/cleanup-temp-files'>;
}
declare module 'bugsnag-sourcemaps/lib/cli-logger.js' {
  declare module.exports: $Exports<'bugsnag-sourcemaps/lib/cli-logger'>;
}
declare module 'bugsnag-sourcemaps/lib/does-file-exist.js' {
  declare module.exports: $Exports<'bugsnag-sourcemaps/lib/does-file-exist'>;
}
declare module 'bugsnag-sourcemaps/lib/get-app-version.js' {
  declare module.exports: $Exports<'bugsnag-sourcemaps/lib/get-app-version'>;
}
declare module 'bugsnag-sourcemaps/lib/options.js' {
  declare module.exports: $Exports<'bugsnag-sourcemaps/lib/options'>;
}
declare module 'bugsnag-sourcemaps/lib/prepare-request.js' {
  declare module.exports: $Exports<'bugsnag-sourcemaps/lib/prepare-request'>;
}
declare module 'bugsnag-sourcemaps/lib/read-file-json.js' {
  declare module.exports: $Exports<'bugsnag-sourcemaps/lib/read-file-json'>;
}
declare module 'bugsnag-sourcemaps/lib/request.js' {
  declare module.exports: $Exports<'bugsnag-sourcemaps/lib/request'>;
}
declare module 'bugsnag-sourcemaps/lib/strip-project-root.js' {
  declare module.exports: $Exports<'bugsnag-sourcemaps/lib/strip-project-root'>;
}
declare module 'bugsnag-sourcemaps/lib/test/options.test.js' {
  declare module.exports: $Exports<'bugsnag-sourcemaps/lib/test/options.test'>;
}
declare module 'bugsnag-sourcemaps/lib/test/prepare-request.test.js' {
  declare module.exports: $Exports<'bugsnag-sourcemaps/lib/test/prepare-request.test'>;
}
declare module 'bugsnag-sourcemaps/lib/test/strip-project-root.test.js' {
  declare module.exports: $Exports<'bugsnag-sourcemaps/lib/test/strip-project-root.test'>;
}
