// flow-typed signature: bda0fd7e6c3ae80b5ef93c55213dd284
// flow-typed version: <<STUB>>/capture-exit_v^2.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'capture-exit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'capture-exit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'capture-exit/index' {
  declare module.exports: $Exports<'capture-exit'>;
}
declare module 'capture-exit/index.js' {
  declare module.exports: $Exports<'capture-exit'>;
}
