// flow-typed signature: b9eb8815804a4029e150bf2767c7f9ba
// flow-typed version: <<STUB>>/clone-deep_v^4.0.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clone-deep'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clone-deep' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'clone-deep/index' {
  declare module.exports: $Exports<'clone-deep'>;
}
declare module 'clone-deep/index.js' {
  declare module.exports: $Exports<'clone-deep'>;
}
