// flow-typed signature: 5096806d875ce96d6e63402a3d1b7998
// flow-typed version: <<STUB>>/compare-versions_v^3.6.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compare-versions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compare-versions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'compare-versions/index' {
  declare module.exports: $Exports<'compare-versions'>;
}
declare module 'compare-versions/index.js' {
  declare module.exports: $Exports<'compare-versions'>;
}
