// flow-typed signature: 22b163cadd5d9d6d81c9db1dcd499b3e
// flow-typed version: <<STUB>>/d3-dsv_v^1.1.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-dsv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-dsv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-dsv/dist/d3-dsv' {
  declare module.exports: any;
}

declare module 'd3-dsv/dist/d3-dsv.min' {
  declare module.exports: any;
}

declare module 'd3-dsv/src/autoType' {
  declare module.exports: any;
}

declare module 'd3-dsv/src/csv' {
  declare module.exports: any;
}

declare module 'd3-dsv/src/dsv' {
  declare module.exports: any;
}

declare module 'd3-dsv/src' {
  declare module.exports: any;
}

declare module 'd3-dsv/src/tsv' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-dsv/dist/d3-dsv.js' {
  declare module.exports: $Exports<'d3-dsv/dist/d3-dsv'>;
}
declare module 'd3-dsv/dist/d3-dsv.min.js' {
  declare module.exports: $Exports<'d3-dsv/dist/d3-dsv.min'>;
}
declare module 'd3-dsv/src/autoType.js' {
  declare module.exports: $Exports<'d3-dsv/src/autoType'>;
}
declare module 'd3-dsv/src/csv.js' {
  declare module.exports: $Exports<'d3-dsv/src/csv'>;
}
declare module 'd3-dsv/src/dsv.js' {
  declare module.exports: $Exports<'d3-dsv/src/dsv'>;
}
declare module 'd3-dsv/src/index' {
  declare module.exports: $Exports<'d3-dsv/src'>;
}
declare module 'd3-dsv/src/index.js' {
  declare module.exports: $Exports<'d3-dsv/src'>;
}
declare module 'd3-dsv/src/tsv.js' {
  declare module.exports: $Exports<'d3-dsv/src/tsv'>;
}
