// flow-typed signature: 2a9588d3d8817033e84241d022e67122
// flow-typed version: <<STUB>>/dependency-check_v^3.4.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dependency-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dependency-check' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dependency-check/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dependency-check/cli.js' {
  declare module.exports: $Exports<'dependency-check/cli'>;
}
declare module 'dependency-check/index' {
  declare module.exports: $Exports<'dependency-check'>;
}
declare module 'dependency-check/index.js' {
  declare module.exports: $Exports<'dependency-check'>;
}
