// flow-typed signature: 081705abe50fb6e20efc7242b434e723
// flow-typed version: <<STUB>>/domain-ping_v^0.1.10/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'domain-ping'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'domain-ping' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'domain-ping/domain-ping' {
  declare module.exports: any;
}

declare module 'domain-ping/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'domain-ping/domain-ping.js' {
  declare module.exports: $Exports<'domain-ping/domain-ping'>;
}
declare module 'domain-ping/test/test.js' {
  declare module.exports: $Exports<'domain-ping/test/test'>;
}
