// flow-typed signature: ce75d3c5da37e2794fd8c280165ae07b
// flow-typed version: <<STUB>>/ecstatic_v^2.2.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ecstatic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ecstatic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ecstatic/example/core' {
  declare module.exports: any;
}

declare module 'ecstatic/example/express' {
  declare module.exports: any;
}

declare module 'ecstatic/example/union' {
  declare module.exports: any;
}

declare module 'ecstatic/lib/ecstatic' {
  declare module.exports: any;
}

declare module 'ecstatic/lib/ecstatic/etag' {
  declare module.exports: any;
}

declare module 'ecstatic/lib/ecstatic/opts' {
  declare module.exports: any;
}

declare module 'ecstatic/lib/ecstatic/show-dir' {
  declare module.exports: any;
}

declare module 'ecstatic/lib/ecstatic/show-dir/perms-to-string' {
  declare module.exports: any;
}

declare module 'ecstatic/lib/ecstatic/show-dir/size-to-string' {
  declare module.exports: any;
}

declare module 'ecstatic/lib/ecstatic/show-dir/sort-files' {
  declare module.exports: any;
}

declare module 'ecstatic/lib/ecstatic/show-dir/styles' {
  declare module.exports: any;
}

declare module 'ecstatic/lib/ecstatic/status-handlers' {
  declare module.exports: any;
}

declare module 'ecstatic/tools/build-icons' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ecstatic/example/core.js' {
  declare module.exports: $Exports<'ecstatic/example/core'>;
}
declare module 'ecstatic/example/express.js' {
  declare module.exports: $Exports<'ecstatic/example/express'>;
}
declare module 'ecstatic/example/union.js' {
  declare module.exports: $Exports<'ecstatic/example/union'>;
}
declare module 'ecstatic/lib/ecstatic.js' {
  declare module.exports: $Exports<'ecstatic/lib/ecstatic'>;
}
declare module 'ecstatic/lib/ecstatic/etag.js' {
  declare module.exports: $Exports<'ecstatic/lib/ecstatic/etag'>;
}
declare module 'ecstatic/lib/ecstatic/opts.js' {
  declare module.exports: $Exports<'ecstatic/lib/ecstatic/opts'>;
}
declare module 'ecstatic/lib/ecstatic/show-dir/index' {
  declare module.exports: $Exports<'ecstatic/lib/ecstatic/show-dir'>;
}
declare module 'ecstatic/lib/ecstatic/show-dir/index.js' {
  declare module.exports: $Exports<'ecstatic/lib/ecstatic/show-dir'>;
}
declare module 'ecstatic/lib/ecstatic/show-dir/perms-to-string.js' {
  declare module.exports: $Exports<'ecstatic/lib/ecstatic/show-dir/perms-to-string'>;
}
declare module 'ecstatic/lib/ecstatic/show-dir/size-to-string.js' {
  declare module.exports: $Exports<'ecstatic/lib/ecstatic/show-dir/size-to-string'>;
}
declare module 'ecstatic/lib/ecstatic/show-dir/sort-files.js' {
  declare module.exports: $Exports<'ecstatic/lib/ecstatic/show-dir/sort-files'>;
}
declare module 'ecstatic/lib/ecstatic/show-dir/styles.js' {
  declare module.exports: $Exports<'ecstatic/lib/ecstatic/show-dir/styles'>;
}
declare module 'ecstatic/lib/ecstatic/status-handlers.js' {
  declare module.exports: $Exports<'ecstatic/lib/ecstatic/status-handlers'>;
}
declare module 'ecstatic/tools/build-icons.js' {
  declare module.exports: $Exports<'ecstatic/tools/build-icons'>;
}
