// flow-typed signature: 6f501df90d458c4be160a7def0feeeab
// flow-typed version: <<STUB>>/electron-rabbit_v^1.0.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-rabbit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-rabbit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-rabbit/example/app' {
  declare module.exports: any;
}

declare module 'electron-rabbit/example/background' {
  declare module.exports: any;
}

declare module 'electron-rabbit/example/client-preload' {
  declare module.exports: any;
}

declare module 'electron-rabbit/example/client' {
  declare module.exports: any;
}

declare module 'electron-rabbit/example/my-app-ipc' {
  declare module.exports: any;
}

declare module 'electron-rabbit/src/background-ipc' {
  declare module.exports: any;
}

declare module 'electron-rabbit/src/client-ipc' {
  declare module.exports: any;
}

declare module 'electron-rabbit/src/find-open-socket' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-rabbit/example/app.js' {
  declare module.exports: $Exports<'electron-rabbit/example/app'>;
}
declare module 'electron-rabbit/example/background.js' {
  declare module.exports: $Exports<'electron-rabbit/example/background'>;
}
declare module 'electron-rabbit/example/client-preload.js' {
  declare module.exports: $Exports<'electron-rabbit/example/client-preload'>;
}
declare module 'electron-rabbit/example/client.js' {
  declare module.exports: $Exports<'electron-rabbit/example/client'>;
}
declare module 'electron-rabbit/example/my-app-ipc.js' {
  declare module.exports: $Exports<'electron-rabbit/example/my-app-ipc'>;
}
declare module 'electron-rabbit/index' {
  declare module.exports: $Exports<'electron-rabbit'>;
}
declare module 'electron-rabbit/index.js' {
  declare module.exports: $Exports<'electron-rabbit'>;
}
declare module 'electron-rabbit/src/background-ipc.js' {
  declare module.exports: $Exports<'electron-rabbit/src/background-ipc'>;
}
declare module 'electron-rabbit/src/client-ipc.js' {
  declare module.exports: $Exports<'electron-rabbit/src/client-ipc'>;
}
declare module 'electron-rabbit/src/find-open-socket.js' {
  declare module.exports: $Exports<'electron-rabbit/src/find-open-socket'>;
}
