// flow-typed signature: dbe19c2c14206fb3c17757a4d1d46ed4
// flow-typed version: <<STUB>>/electron-timber_v^0.5.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-timber'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-timber' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-timber/preload' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-timber/index' {
  declare module.exports: $Exports<'electron-timber'>;
}
declare module 'electron-timber/index.js' {
  declare module.exports: $Exports<'electron-timber'>;
}
declare module 'electron-timber/preload.js' {
  declare module.exports: $Exports<'electron-timber/preload'>;
}
