// flow-typed signature: d46f28abb653884e8633c86dcf87e9f6
// flow-typed version: <<STUB>>/eslint-config-prettier-standard_v^3.0.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-prettier-standard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-prettier-standard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-prettier-standard/base' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier-standard/end' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier-standard/eslint-file-base' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier-standard/eslint-file' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier-standard/lib/base' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier-standard/lib/prettier-standard' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier-standard/prettier-file-base' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier-standard/prettier-file' {
  declare module.exports: any;
}

declare module 'eslint-config-prettier-standard/prettierrc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-prettier-standard/base.js' {
  declare module.exports: $Exports<'eslint-config-prettier-standard/base'>;
}
declare module 'eslint-config-prettier-standard/end.js' {
  declare module.exports: $Exports<'eslint-config-prettier-standard/end'>;
}
declare module 'eslint-config-prettier-standard/eslint-file-base.js' {
  declare module.exports: $Exports<'eslint-config-prettier-standard/eslint-file-base'>;
}
declare module 'eslint-config-prettier-standard/eslint-file.js' {
  declare module.exports: $Exports<'eslint-config-prettier-standard/eslint-file'>;
}
declare module 'eslint-config-prettier-standard/index' {
  declare module.exports: $Exports<'eslint-config-prettier-standard'>;
}
declare module 'eslint-config-prettier-standard/index.js' {
  declare module.exports: $Exports<'eslint-config-prettier-standard'>;
}
declare module 'eslint-config-prettier-standard/lib/base.js' {
  declare module.exports: $Exports<'eslint-config-prettier-standard/lib/base'>;
}
declare module 'eslint-config-prettier-standard/lib/prettier-standard.js' {
  declare module.exports: $Exports<'eslint-config-prettier-standard/lib/prettier-standard'>;
}
declare module 'eslint-config-prettier-standard/prettier-file-base.js' {
  declare module.exports: $Exports<'eslint-config-prettier-standard/prettier-file-base'>;
}
declare module 'eslint-config-prettier-standard/prettier-file.js' {
  declare module.exports: $Exports<'eslint-config-prettier-standard/prettier-file'>;
}
declare module 'eslint-config-prettier-standard/prettierrc.js' {
  declare module.exports: $Exports<'eslint-config-prettier-standard/prettierrc'>;
}
