// flow-typed signature: 2397baffe3a4f0215c28109365de87b9
// flow-typed version: <<STUB>>/flow-geojson_v^2.0.7/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-geojson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-geojson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-geojson/lib/GeoJSON' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-geojson/lib/GeoJSON.js' {
  declare module.exports: $Exports<'flow-geojson/lib/GeoJSON'>;
}
