// flow-typed signature: 81b8036ad717f26108d477e940db6041
// flow-typed version: <<STUB>>/fs-write-stream-atomic_v^1.0.10/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs-write-stream-atomic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs-write-stream-atomic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fs-write-stream-atomic/test/basic' {
  declare module.exports: any;
}

declare module 'fs-write-stream-atomic/test/chown' {
  declare module.exports: any;
}

declare module 'fs-write-stream-atomic/test/rename-eperm' {
  declare module.exports: any;
}

declare module 'fs-write-stream-atomic/test/rename-fail' {
  declare module.exports: any;
}

declare module 'fs-write-stream-atomic/test/slow-close' {
  declare module.exports: any;
}

declare module 'fs-write-stream-atomic/test/toolong' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fs-write-stream-atomic/index' {
  declare module.exports: $Exports<'fs-write-stream-atomic'>;
}
declare module 'fs-write-stream-atomic/index.js' {
  declare module.exports: $Exports<'fs-write-stream-atomic'>;
}
declare module 'fs-write-stream-atomic/test/basic.js' {
  declare module.exports: $Exports<'fs-write-stream-atomic/test/basic'>;
}
declare module 'fs-write-stream-atomic/test/chown.js' {
  declare module.exports: $Exports<'fs-write-stream-atomic/test/chown'>;
}
declare module 'fs-write-stream-atomic/test/rename-eperm.js' {
  declare module.exports: $Exports<'fs-write-stream-atomic/test/rename-eperm'>;
}
declare module 'fs-write-stream-atomic/test/rename-fail.js' {
  declare module.exports: $Exports<'fs-write-stream-atomic/test/rename-fail'>;
}
declare module 'fs-write-stream-atomic/test/slow-close.js' {
  declare module.exports: $Exports<'fs-write-stream-atomic/test/slow-close'>;
}
declare module 'fs-write-stream-atomic/test/toolong.js' {
  declare module.exports: $Exports<'fs-write-stream-atomic/test/toolong'>;
}
