// flow-typed signature: f192fd345d4e7659c458b83ab5a95ecc
// flow-typed version: <<STUB>>/get-scrollbar-width_v^1.0.4/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-scrollbar-width'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'get-scrollbar-width' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'get-scrollbar-width/index' {
  declare module.exports: $Exports<'get-scrollbar-width'>;
}
declare module 'get-scrollbar-width/index.js' {
  declare module.exports: $Exports<'get-scrollbar-width'>;
}
