// flow-typed signature: 9e1bf59a1da1aed92b38ce90da28fbd6
// flow-typed version: <<STUB>>/html-react-parser_v^0.9.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-react-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-react-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-react-parser/dist/html-react-parser' {
  declare module.exports: any;
}

declare module 'html-react-parser/dist/html-react-parser.min' {
  declare module.exports: any;
}

declare module 'html-react-parser/lib/attributes-to-props' {
  declare module.exports: any;
}

declare module 'html-react-parser/lib/dom-to-react' {
  declare module.exports: any;
}

declare module 'html-react-parser/lib/utilities' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-react-parser/dist/html-react-parser.js' {
  declare module.exports: $Exports<'html-react-parser/dist/html-react-parser'>;
}
declare module 'html-react-parser/dist/html-react-parser.min.js' {
  declare module.exports: $Exports<'html-react-parser/dist/html-react-parser.min'>;
}
declare module 'html-react-parser/index' {
  declare module.exports: $Exports<'html-react-parser'>;
}
declare module 'html-react-parser/index.js' {
  declare module.exports: $Exports<'html-react-parser'>;
}
declare module 'html-react-parser/lib/attributes-to-props.js' {
  declare module.exports: $Exports<'html-react-parser/lib/attributes-to-props'>;
}
declare module 'html-react-parser/lib/dom-to-react.js' {
  declare module.exports: $Exports<'html-react-parser/lib/dom-to-react'>;
}
declare module 'html-react-parser/lib/utilities.js' {
  declare module.exports: $Exports<'html-react-parser/lib/utilities'>;
}
