// flow-typed signature: 605647edde4467980bebdf93099a7453
// flow-typed version: <<STUB>>/hubfs.js_v^1.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hubfs.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hubfs.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hubfs.js/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hubfs.js/index' {
  declare module.exports: $Exports<'hubfs.js'>;
}
declare module 'hubfs.js/index.js' {
  declare module.exports: $Exports<'hubfs.js'>;
}
declare module 'hubfs.js/test.js' {
  declare module.exports: $Exports<'hubfs.js/test'>;
}
