// flow-typed signature: 32e06da67a2e2ae0cfbc4d529c96702f
// flow-typed version: <<STUB>>/hyperquest_v^2.1.3/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hyperquest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hyperquest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hyperquest/example/many_hyperquest' {
  declare module.exports: any;
}

declare module 'hyperquest/example/many_request' {
  declare module.exports: any;
}

declare module 'hyperquest/example/req' {
  declare module.exports: any;
}

declare module 'hyperquest/test/auth_encoded' {
  declare module.exports: any;
}

declare module 'hyperquest/test/auth_opt' {
  declare module.exports: any;
}

declare module 'hyperquest/test/auth' {
  declare module.exports: any;
}

declare module 'hyperquest/test/get' {
  declare module.exports: any;
}

declare module 'hyperquest/test/many' {
  declare module.exports: any;
}

declare module 'hyperquest/test/opts' {
  declare module.exports: any;
}

declare module 'hyperquest/test/post_immediate' {
  declare module.exports: any;
}

declare module 'hyperquest/test/post' {
  declare module.exports: any;
}

declare module 'hyperquest/test/readable' {
  declare module.exports: any;
}

declare module 'hyperquest/test/set_header' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hyperquest/example/many_hyperquest.js' {
  declare module.exports: $Exports<'hyperquest/example/many_hyperquest'>;
}
declare module 'hyperquest/example/many_request.js' {
  declare module.exports: $Exports<'hyperquest/example/many_request'>;
}
declare module 'hyperquest/example/req.js' {
  declare module.exports: $Exports<'hyperquest/example/req'>;
}
declare module 'hyperquest/index' {
  declare module.exports: $Exports<'hyperquest'>;
}
declare module 'hyperquest/index.js' {
  declare module.exports: $Exports<'hyperquest'>;
}
declare module 'hyperquest/test/auth_encoded.js' {
  declare module.exports: $Exports<'hyperquest/test/auth_encoded'>;
}
declare module 'hyperquest/test/auth_opt.js' {
  declare module.exports: $Exports<'hyperquest/test/auth_opt'>;
}
declare module 'hyperquest/test/auth.js' {
  declare module.exports: $Exports<'hyperquest/test/auth'>;
}
declare module 'hyperquest/test/get.js' {
  declare module.exports: $Exports<'hyperquest/test/get'>;
}
declare module 'hyperquest/test/many.js' {
  declare module.exports: $Exports<'hyperquest/test/many'>;
}
declare module 'hyperquest/test/opts.js' {
  declare module.exports: $Exports<'hyperquest/test/opts'>;
}
declare module 'hyperquest/test/post_immediate.js' {
  declare module.exports: $Exports<'hyperquest/test/post_immediate'>;
}
declare module 'hyperquest/test/post.js' {
  declare module.exports: $Exports<'hyperquest/test/post'>;
}
declare module 'hyperquest/test/readable.js' {
  declare module.exports: $Exports<'hyperquest/test/readable'>;
}
declare module 'hyperquest/test/set_header.js' {
  declare module.exports: $Exports<'hyperquest/test/set_header'>;
}
