// flow-typed signature: 94b8c8a80a285df424f309c0e030ec1d
// flow-typed version: <<STUB>>/id-mapeo_v^3.3.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'id-mapeo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'id-mapeo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'id-mapeo/build_css' {
  declare module.exports: any;
}

declare module 'id-mapeo/build_data' {
  declare module.exports: any;
}

declare module 'id-mapeo/build_src' {
  declare module.exports: any;
}

declare module 'id-mapeo/data' {
  declare module.exports: any;
}

declare module 'id-mapeo/data/update_imagery' {
  declare module.exports: any;
}

declare module 'id-mapeo/data/update_locales' {
  declare module.exports: any;
}

declare module 'id-mapeo/development_server' {
  declare module.exports: any;
}

declare module 'id-mapeo/dist/iD' {
  declare module.exports: any;
}

declare module 'id-mapeo/dist/iD.min' {
  declare module.exports: any;
}

declare module 'id-mapeo/dist/mapillary-js/mapillary' {
  declare module.exports: any;
}

declare module 'id-mapeo/dist/mapillary-js/mapillary.min' {
  declare module.exports: any;
}

declare module 'id-mapeo/dist/pannellum-streetside/pannellum' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/add_entity' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/add_member' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/add_midpoint' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/add_vertex' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/change_member' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/change_preset' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/change_tags' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/circularize' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/connect' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/copy_entities' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/delete_member' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/delete_multiple' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/delete_node' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/delete_relation' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/delete_way' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/discard_tags' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/disconnect' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/extract' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/join' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/merge_nodes' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/merge_polygon' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/merge_remote_changes' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/merge' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/move_member' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/move_node' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/move' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/noop' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/orthogonalize' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/reflect' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/restrict_turn' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/reverse' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/revert' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/rotate' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/split' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/straighten_nodes' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/straighten_way' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/unrestrict_turn' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/actions/upgrade_tags' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior/add_way' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior/breathe' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior/copy' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior/drag' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior/draw_way' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior/draw' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior/edit' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior/hash' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior/hover' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior/lasso' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior/operation' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior/paste' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior/select' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/behavior/tail' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/core/context' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/core/difference' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/core/graph' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/core/history' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/core' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/core/tree' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/core/validation' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/core/validation/models' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/core/validator' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/geo/extent' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/geo/geo' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/geo/geom' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/geo' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/geo/ortho' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/geo/raw_mercator' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/geo/vector' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/id' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/add_area' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/add_line' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/add_note' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/add_point' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/browse' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/drag_node' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/drag_note' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/draw_area' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/draw_line' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/move' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/rotate' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/save' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/select_data' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/select_error' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/select_note' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/modes/select' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations/circularize' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations/continue' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations/delete' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations/disconnect' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations/downgrade' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations/extract' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations/merge' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations/move' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations/orthogonalize' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations/reflect' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations/reverse' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations/rotate' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations/split' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/operations/straighten' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/osm/auth' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/osm/changeset' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/osm/entity' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/osm' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/osm/intersection' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/osm/lanes' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/osm/multipolygon' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/osm/node' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/osm/note' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/osm/qa_error' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/osm/relation' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/osm/tags' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/osm/way' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/presets/category' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/presets/collection' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/presets/field' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/presets' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/presets/preset' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/renderer/background_source' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/renderer/background' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/renderer/features' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/renderer' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/renderer/map' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/renderer/photos' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/renderer/tile_layer' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/services/improveOSM' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/services' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/services/keepRight' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/services/mapillary' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/services/maprules' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/services/nominatim' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/services/openstreetcam' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/services/osm_wikibase' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/services/osm' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/services/streetside' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/services/taginfo' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/services/vector_tile' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/services/wikidata' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/services/wikipedia' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/areas' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/data' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/debug' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/defs' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/geolocate' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/helpers' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/icon' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/improveOSM' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/keepRight' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/labels' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/layers' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/lines' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/mapillary_images' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/mapillary_signs' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/midpoints' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/notes' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/openstreetcam_images' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/osm' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/points' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/streetside' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/tag_classes' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/touch' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/turns' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/svg/vertices' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/account' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/attribution' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/background_display_options' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/background_offset' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/background' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/changeset_editor' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/cmd' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/combobox' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/commit_changes' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/commit_warnings' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/commit' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/confirm' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/conflicts' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/contributors' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/curtain' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/data_editor' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/data_header' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/disclosure' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/edit_menu' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/entity_editor' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/entity_issues' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/feature_info' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/feature_list' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/field_help' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/field' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields/access' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields/address' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields/check' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields/combo' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields/cycleway' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields/input' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields/lanes' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields/localized' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields/maxspeed' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields/radio' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields/restrictions' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields/textarea' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields/wikidata' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/fields/wikipedia' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/flash' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/form_fields' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/full_screen' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/geolocate' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/help' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/improveOSM_comments' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/improveOSM_details' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/improveOSM_editor' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/improveOSM_header' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/info' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/init' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/inspector' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/intro/area' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/intro/building' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/intro/helper' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/intro' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/intro/intro' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/intro/line' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/intro/navigation' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/intro/point' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/intro/start_editing' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/intro/welcome' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/issues' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/keepRight_details' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/keepRight_editor' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/keepRight_header' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/lasso' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/loading' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/map_data' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/map_in_map' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/modal' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/note_comments' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/note_editor' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/note_header' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/note_report' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/notice' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/panels/background' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/panels/history' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/panels' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/panels/location' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/panels/measurement' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/photoviewer' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/preset_editor' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/preset_favorite_button' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/preset_icon' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/preset_list' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/quick_links' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/radial_menu' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/raw_member_editor' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/raw_membership_editor' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/raw_tag_editor' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/restore' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/scale' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/selection_list' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/settings/custom_background' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/settings/custom_data' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/settings' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/shortcuts' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/sidebar' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/source_switch' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/spinner' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/splash' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/status' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/success' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/tag_reference' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/toggle' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/tools/add_favorite' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/tools/add_recent' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/tools' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/tools/modes' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/tools/notes' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/tools/save' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/tools/search_add' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/tools/sidebar_toggle' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/tools/undo_redo' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/tooltipHtml' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/top_toolbar' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/version' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/view_on_keepRight' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/view_on_osm' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/ui/zoom' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/array' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/bind_once' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/clean_tags' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/detect' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/dimensions' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/get_set_value' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/jsonp_request' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/jxon' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/keybinding' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/locale' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/object' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/rebind' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/session_mutex' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/svg_paths_rtl_fix' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/tiler' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/tooltip' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/trigger_event' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/units' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/util/util' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/almost_junction' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/close_nodes' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/crossing_ways' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/disconnected_way' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/fixme_tag' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/generic_name' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/impossible_oneway' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/incompatible_source' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/invalid_format' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/maprules' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/missing_role' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/missing_tag' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/outdated_tags' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/private_data' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/tag_suggests_area' {
  declare module.exports: any;
}

declare module 'id-mapeo/modules/validations/unsquare_way' {
  declare module.exports: any;
}

declare module 'id-mapeo/monkey_patches/patch-locales' {
  declare module.exports: any;
}

// Filename aliases
declare module 'id-mapeo/build_css.js' {
  declare module.exports: $Exports<'id-mapeo/build_css'>;
}
declare module 'id-mapeo/build_data.js' {
  declare module.exports: $Exports<'id-mapeo/build_data'>;
}
declare module 'id-mapeo/build_src.js' {
  declare module.exports: $Exports<'id-mapeo/build_src'>;
}
declare module 'id-mapeo/data/index' {
  declare module.exports: $Exports<'id-mapeo/data'>;
}
declare module 'id-mapeo/data/index.js' {
  declare module.exports: $Exports<'id-mapeo/data'>;
}
declare module 'id-mapeo/data/update_imagery.js' {
  declare module.exports: $Exports<'id-mapeo/data/update_imagery'>;
}
declare module 'id-mapeo/data/update_locales.js' {
  declare module.exports: $Exports<'id-mapeo/data/update_locales'>;
}
declare module 'id-mapeo/development_server.js' {
  declare module.exports: $Exports<'id-mapeo/development_server'>;
}
declare module 'id-mapeo/dist/iD.js' {
  declare module.exports: $Exports<'id-mapeo/dist/iD'>;
}
declare module 'id-mapeo/dist/iD.min.js' {
  declare module.exports: $Exports<'id-mapeo/dist/iD.min'>;
}
declare module 'id-mapeo/dist/mapillary-js/mapillary.js' {
  declare module.exports: $Exports<'id-mapeo/dist/mapillary-js/mapillary'>;
}
declare module 'id-mapeo/dist/mapillary-js/mapillary.min.js' {
  declare module.exports: $Exports<'id-mapeo/dist/mapillary-js/mapillary.min'>;
}
declare module 'id-mapeo/dist/pannellum-streetside/pannellum.js' {
  declare module.exports: $Exports<'id-mapeo/dist/pannellum-streetside/pannellum'>;
}
declare module 'id-mapeo/modules/actions/add_entity.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/add_entity'>;
}
declare module 'id-mapeo/modules/actions/add_member.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/add_member'>;
}
declare module 'id-mapeo/modules/actions/add_midpoint.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/add_midpoint'>;
}
declare module 'id-mapeo/modules/actions/add_vertex.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/add_vertex'>;
}
declare module 'id-mapeo/modules/actions/change_member.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/change_member'>;
}
declare module 'id-mapeo/modules/actions/change_preset.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/change_preset'>;
}
declare module 'id-mapeo/modules/actions/change_tags.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/change_tags'>;
}
declare module 'id-mapeo/modules/actions/circularize.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/circularize'>;
}
declare module 'id-mapeo/modules/actions/connect.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/connect'>;
}
declare module 'id-mapeo/modules/actions/copy_entities.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/copy_entities'>;
}
declare module 'id-mapeo/modules/actions/delete_member.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/delete_member'>;
}
declare module 'id-mapeo/modules/actions/delete_multiple.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/delete_multiple'>;
}
declare module 'id-mapeo/modules/actions/delete_node.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/delete_node'>;
}
declare module 'id-mapeo/modules/actions/delete_relation.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/delete_relation'>;
}
declare module 'id-mapeo/modules/actions/delete_way.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/delete_way'>;
}
declare module 'id-mapeo/modules/actions/discard_tags.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/discard_tags'>;
}
declare module 'id-mapeo/modules/actions/disconnect.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/disconnect'>;
}
declare module 'id-mapeo/modules/actions/extract.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/extract'>;
}
declare module 'id-mapeo/modules/actions/index' {
  declare module.exports: $Exports<'id-mapeo/modules/actions'>;
}
declare module 'id-mapeo/modules/actions/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions'>;
}
declare module 'id-mapeo/modules/actions/join.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/join'>;
}
declare module 'id-mapeo/modules/actions/merge_nodes.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/merge_nodes'>;
}
declare module 'id-mapeo/modules/actions/merge_polygon.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/merge_polygon'>;
}
declare module 'id-mapeo/modules/actions/merge_remote_changes.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/merge_remote_changes'>;
}
declare module 'id-mapeo/modules/actions/merge.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/merge'>;
}
declare module 'id-mapeo/modules/actions/move_member.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/move_member'>;
}
declare module 'id-mapeo/modules/actions/move_node.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/move_node'>;
}
declare module 'id-mapeo/modules/actions/move.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/move'>;
}
declare module 'id-mapeo/modules/actions/noop.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/noop'>;
}
declare module 'id-mapeo/modules/actions/orthogonalize.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/orthogonalize'>;
}
declare module 'id-mapeo/modules/actions/reflect.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/reflect'>;
}
declare module 'id-mapeo/modules/actions/restrict_turn.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/restrict_turn'>;
}
declare module 'id-mapeo/modules/actions/reverse.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/reverse'>;
}
declare module 'id-mapeo/modules/actions/revert.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/revert'>;
}
declare module 'id-mapeo/modules/actions/rotate.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/rotate'>;
}
declare module 'id-mapeo/modules/actions/split.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/split'>;
}
declare module 'id-mapeo/modules/actions/straighten_nodes.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/straighten_nodes'>;
}
declare module 'id-mapeo/modules/actions/straighten_way.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/straighten_way'>;
}
declare module 'id-mapeo/modules/actions/unrestrict_turn.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/unrestrict_turn'>;
}
declare module 'id-mapeo/modules/actions/upgrade_tags.js' {
  declare module.exports: $Exports<'id-mapeo/modules/actions/upgrade_tags'>;
}
declare module 'id-mapeo/modules/behavior/add_way.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior/add_way'>;
}
declare module 'id-mapeo/modules/behavior/breathe.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior/breathe'>;
}
declare module 'id-mapeo/modules/behavior/copy.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior/copy'>;
}
declare module 'id-mapeo/modules/behavior/drag.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior/drag'>;
}
declare module 'id-mapeo/modules/behavior/draw_way.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior/draw_way'>;
}
declare module 'id-mapeo/modules/behavior/draw.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior/draw'>;
}
declare module 'id-mapeo/modules/behavior/edit.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior/edit'>;
}
declare module 'id-mapeo/modules/behavior/hash.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior/hash'>;
}
declare module 'id-mapeo/modules/behavior/hover.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior/hover'>;
}
declare module 'id-mapeo/modules/behavior/index' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior'>;
}
declare module 'id-mapeo/modules/behavior/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior'>;
}
declare module 'id-mapeo/modules/behavior/lasso.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior/lasso'>;
}
declare module 'id-mapeo/modules/behavior/operation.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior/operation'>;
}
declare module 'id-mapeo/modules/behavior/paste.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior/paste'>;
}
declare module 'id-mapeo/modules/behavior/select.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior/select'>;
}
declare module 'id-mapeo/modules/behavior/tail.js' {
  declare module.exports: $Exports<'id-mapeo/modules/behavior/tail'>;
}
declare module 'id-mapeo/modules/core/context.js' {
  declare module.exports: $Exports<'id-mapeo/modules/core/context'>;
}
declare module 'id-mapeo/modules/core/difference.js' {
  declare module.exports: $Exports<'id-mapeo/modules/core/difference'>;
}
declare module 'id-mapeo/modules/core/graph.js' {
  declare module.exports: $Exports<'id-mapeo/modules/core/graph'>;
}
declare module 'id-mapeo/modules/core/history.js' {
  declare module.exports: $Exports<'id-mapeo/modules/core/history'>;
}
declare module 'id-mapeo/modules/core/index' {
  declare module.exports: $Exports<'id-mapeo/modules/core'>;
}
declare module 'id-mapeo/modules/core/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/core'>;
}
declare module 'id-mapeo/modules/core/tree.js' {
  declare module.exports: $Exports<'id-mapeo/modules/core/tree'>;
}
declare module 'id-mapeo/modules/core/validation/index' {
  declare module.exports: $Exports<'id-mapeo/modules/core/validation'>;
}
declare module 'id-mapeo/modules/core/validation/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/core/validation'>;
}
declare module 'id-mapeo/modules/core/validation/models.js' {
  declare module.exports: $Exports<'id-mapeo/modules/core/validation/models'>;
}
declare module 'id-mapeo/modules/core/validator.js' {
  declare module.exports: $Exports<'id-mapeo/modules/core/validator'>;
}
declare module 'id-mapeo/modules/geo/extent.js' {
  declare module.exports: $Exports<'id-mapeo/modules/geo/extent'>;
}
declare module 'id-mapeo/modules/geo/geo.js' {
  declare module.exports: $Exports<'id-mapeo/modules/geo/geo'>;
}
declare module 'id-mapeo/modules/geo/geom.js' {
  declare module.exports: $Exports<'id-mapeo/modules/geo/geom'>;
}
declare module 'id-mapeo/modules/geo/index' {
  declare module.exports: $Exports<'id-mapeo/modules/geo'>;
}
declare module 'id-mapeo/modules/geo/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/geo'>;
}
declare module 'id-mapeo/modules/geo/ortho.js' {
  declare module.exports: $Exports<'id-mapeo/modules/geo/ortho'>;
}
declare module 'id-mapeo/modules/geo/raw_mercator.js' {
  declare module.exports: $Exports<'id-mapeo/modules/geo/raw_mercator'>;
}
declare module 'id-mapeo/modules/geo/vector.js' {
  declare module.exports: $Exports<'id-mapeo/modules/geo/vector'>;
}
declare module 'id-mapeo/modules/id.js' {
  declare module.exports: $Exports<'id-mapeo/modules/id'>;
}
declare module 'id-mapeo/modules/index' {
  declare module.exports: $Exports<'id-mapeo/modules'>;
}
declare module 'id-mapeo/modules/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules'>;
}
declare module 'id-mapeo/modules/modes/add_area.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/add_area'>;
}
declare module 'id-mapeo/modules/modes/add_line.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/add_line'>;
}
declare module 'id-mapeo/modules/modes/add_note.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/add_note'>;
}
declare module 'id-mapeo/modules/modes/add_point.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/add_point'>;
}
declare module 'id-mapeo/modules/modes/browse.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/browse'>;
}
declare module 'id-mapeo/modules/modes/drag_node.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/drag_node'>;
}
declare module 'id-mapeo/modules/modes/drag_note.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/drag_note'>;
}
declare module 'id-mapeo/modules/modes/draw_area.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/draw_area'>;
}
declare module 'id-mapeo/modules/modes/draw_line.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/draw_line'>;
}
declare module 'id-mapeo/modules/modes/index' {
  declare module.exports: $Exports<'id-mapeo/modules/modes'>;
}
declare module 'id-mapeo/modules/modes/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes'>;
}
declare module 'id-mapeo/modules/modes/move.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/move'>;
}
declare module 'id-mapeo/modules/modes/rotate.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/rotate'>;
}
declare module 'id-mapeo/modules/modes/save.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/save'>;
}
declare module 'id-mapeo/modules/modes/select_data.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/select_data'>;
}
declare module 'id-mapeo/modules/modes/select_error.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/select_error'>;
}
declare module 'id-mapeo/modules/modes/select_note.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/select_note'>;
}
declare module 'id-mapeo/modules/modes/select.js' {
  declare module.exports: $Exports<'id-mapeo/modules/modes/select'>;
}
declare module 'id-mapeo/modules/operations/circularize.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations/circularize'>;
}
declare module 'id-mapeo/modules/operations/continue.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations/continue'>;
}
declare module 'id-mapeo/modules/operations/delete.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations/delete'>;
}
declare module 'id-mapeo/modules/operations/disconnect.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations/disconnect'>;
}
declare module 'id-mapeo/modules/operations/downgrade.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations/downgrade'>;
}
declare module 'id-mapeo/modules/operations/extract.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations/extract'>;
}
declare module 'id-mapeo/modules/operations/index' {
  declare module.exports: $Exports<'id-mapeo/modules/operations'>;
}
declare module 'id-mapeo/modules/operations/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations'>;
}
declare module 'id-mapeo/modules/operations/merge.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations/merge'>;
}
declare module 'id-mapeo/modules/operations/move.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations/move'>;
}
declare module 'id-mapeo/modules/operations/orthogonalize.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations/orthogonalize'>;
}
declare module 'id-mapeo/modules/operations/reflect.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations/reflect'>;
}
declare module 'id-mapeo/modules/operations/reverse.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations/reverse'>;
}
declare module 'id-mapeo/modules/operations/rotate.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations/rotate'>;
}
declare module 'id-mapeo/modules/operations/split.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations/split'>;
}
declare module 'id-mapeo/modules/operations/straighten.js' {
  declare module.exports: $Exports<'id-mapeo/modules/operations/straighten'>;
}
declare module 'id-mapeo/modules/osm/auth.js' {
  declare module.exports: $Exports<'id-mapeo/modules/osm/auth'>;
}
declare module 'id-mapeo/modules/osm/changeset.js' {
  declare module.exports: $Exports<'id-mapeo/modules/osm/changeset'>;
}
declare module 'id-mapeo/modules/osm/entity.js' {
  declare module.exports: $Exports<'id-mapeo/modules/osm/entity'>;
}
declare module 'id-mapeo/modules/osm/index' {
  declare module.exports: $Exports<'id-mapeo/modules/osm'>;
}
declare module 'id-mapeo/modules/osm/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/osm'>;
}
declare module 'id-mapeo/modules/osm/intersection.js' {
  declare module.exports: $Exports<'id-mapeo/modules/osm/intersection'>;
}
declare module 'id-mapeo/modules/osm/lanes.js' {
  declare module.exports: $Exports<'id-mapeo/modules/osm/lanes'>;
}
declare module 'id-mapeo/modules/osm/multipolygon.js' {
  declare module.exports: $Exports<'id-mapeo/modules/osm/multipolygon'>;
}
declare module 'id-mapeo/modules/osm/node.js' {
  declare module.exports: $Exports<'id-mapeo/modules/osm/node'>;
}
declare module 'id-mapeo/modules/osm/note.js' {
  declare module.exports: $Exports<'id-mapeo/modules/osm/note'>;
}
declare module 'id-mapeo/modules/osm/qa_error.js' {
  declare module.exports: $Exports<'id-mapeo/modules/osm/qa_error'>;
}
declare module 'id-mapeo/modules/osm/relation.js' {
  declare module.exports: $Exports<'id-mapeo/modules/osm/relation'>;
}
declare module 'id-mapeo/modules/osm/tags.js' {
  declare module.exports: $Exports<'id-mapeo/modules/osm/tags'>;
}
declare module 'id-mapeo/modules/osm/way.js' {
  declare module.exports: $Exports<'id-mapeo/modules/osm/way'>;
}
declare module 'id-mapeo/modules/presets/category.js' {
  declare module.exports: $Exports<'id-mapeo/modules/presets/category'>;
}
declare module 'id-mapeo/modules/presets/collection.js' {
  declare module.exports: $Exports<'id-mapeo/modules/presets/collection'>;
}
declare module 'id-mapeo/modules/presets/field.js' {
  declare module.exports: $Exports<'id-mapeo/modules/presets/field'>;
}
declare module 'id-mapeo/modules/presets/index' {
  declare module.exports: $Exports<'id-mapeo/modules/presets'>;
}
declare module 'id-mapeo/modules/presets/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/presets'>;
}
declare module 'id-mapeo/modules/presets/preset.js' {
  declare module.exports: $Exports<'id-mapeo/modules/presets/preset'>;
}
declare module 'id-mapeo/modules/renderer/background_source.js' {
  declare module.exports: $Exports<'id-mapeo/modules/renderer/background_source'>;
}
declare module 'id-mapeo/modules/renderer/background.js' {
  declare module.exports: $Exports<'id-mapeo/modules/renderer/background'>;
}
declare module 'id-mapeo/modules/renderer/features.js' {
  declare module.exports: $Exports<'id-mapeo/modules/renderer/features'>;
}
declare module 'id-mapeo/modules/renderer/index' {
  declare module.exports: $Exports<'id-mapeo/modules/renderer'>;
}
declare module 'id-mapeo/modules/renderer/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/renderer'>;
}
declare module 'id-mapeo/modules/renderer/map.js' {
  declare module.exports: $Exports<'id-mapeo/modules/renderer/map'>;
}
declare module 'id-mapeo/modules/renderer/photos.js' {
  declare module.exports: $Exports<'id-mapeo/modules/renderer/photos'>;
}
declare module 'id-mapeo/modules/renderer/tile_layer.js' {
  declare module.exports: $Exports<'id-mapeo/modules/renderer/tile_layer'>;
}
declare module 'id-mapeo/modules/services/improveOSM.js' {
  declare module.exports: $Exports<'id-mapeo/modules/services/improveOSM'>;
}
declare module 'id-mapeo/modules/services/index' {
  declare module.exports: $Exports<'id-mapeo/modules/services'>;
}
declare module 'id-mapeo/modules/services/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/services'>;
}
declare module 'id-mapeo/modules/services/keepRight.js' {
  declare module.exports: $Exports<'id-mapeo/modules/services/keepRight'>;
}
declare module 'id-mapeo/modules/services/mapillary.js' {
  declare module.exports: $Exports<'id-mapeo/modules/services/mapillary'>;
}
declare module 'id-mapeo/modules/services/maprules.js' {
  declare module.exports: $Exports<'id-mapeo/modules/services/maprules'>;
}
declare module 'id-mapeo/modules/services/nominatim.js' {
  declare module.exports: $Exports<'id-mapeo/modules/services/nominatim'>;
}
declare module 'id-mapeo/modules/services/openstreetcam.js' {
  declare module.exports: $Exports<'id-mapeo/modules/services/openstreetcam'>;
}
declare module 'id-mapeo/modules/services/osm_wikibase.js' {
  declare module.exports: $Exports<'id-mapeo/modules/services/osm_wikibase'>;
}
declare module 'id-mapeo/modules/services/osm.js' {
  declare module.exports: $Exports<'id-mapeo/modules/services/osm'>;
}
declare module 'id-mapeo/modules/services/streetside.js' {
  declare module.exports: $Exports<'id-mapeo/modules/services/streetside'>;
}
declare module 'id-mapeo/modules/services/taginfo.js' {
  declare module.exports: $Exports<'id-mapeo/modules/services/taginfo'>;
}
declare module 'id-mapeo/modules/services/vector_tile.js' {
  declare module.exports: $Exports<'id-mapeo/modules/services/vector_tile'>;
}
declare module 'id-mapeo/modules/services/wikidata.js' {
  declare module.exports: $Exports<'id-mapeo/modules/services/wikidata'>;
}
declare module 'id-mapeo/modules/services/wikipedia.js' {
  declare module.exports: $Exports<'id-mapeo/modules/services/wikipedia'>;
}
declare module 'id-mapeo/modules/svg/areas.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/areas'>;
}
declare module 'id-mapeo/modules/svg/data.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/data'>;
}
declare module 'id-mapeo/modules/svg/debug.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/debug'>;
}
declare module 'id-mapeo/modules/svg/defs.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/defs'>;
}
declare module 'id-mapeo/modules/svg/geolocate.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/geolocate'>;
}
declare module 'id-mapeo/modules/svg/helpers.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/helpers'>;
}
declare module 'id-mapeo/modules/svg/icon.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/icon'>;
}
declare module 'id-mapeo/modules/svg/improveOSM.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/improveOSM'>;
}
declare module 'id-mapeo/modules/svg/index' {
  declare module.exports: $Exports<'id-mapeo/modules/svg'>;
}
declare module 'id-mapeo/modules/svg/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg'>;
}
declare module 'id-mapeo/modules/svg/keepRight.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/keepRight'>;
}
declare module 'id-mapeo/modules/svg/labels.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/labels'>;
}
declare module 'id-mapeo/modules/svg/layers.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/layers'>;
}
declare module 'id-mapeo/modules/svg/lines.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/lines'>;
}
declare module 'id-mapeo/modules/svg/mapillary_images.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/mapillary_images'>;
}
declare module 'id-mapeo/modules/svg/mapillary_signs.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/mapillary_signs'>;
}
declare module 'id-mapeo/modules/svg/midpoints.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/midpoints'>;
}
declare module 'id-mapeo/modules/svg/notes.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/notes'>;
}
declare module 'id-mapeo/modules/svg/openstreetcam_images.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/openstreetcam_images'>;
}
declare module 'id-mapeo/modules/svg/osm.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/osm'>;
}
declare module 'id-mapeo/modules/svg/points.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/points'>;
}
declare module 'id-mapeo/modules/svg/streetside.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/streetside'>;
}
declare module 'id-mapeo/modules/svg/tag_classes.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/tag_classes'>;
}
declare module 'id-mapeo/modules/svg/touch.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/touch'>;
}
declare module 'id-mapeo/modules/svg/turns.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/turns'>;
}
declare module 'id-mapeo/modules/svg/vertices.js' {
  declare module.exports: $Exports<'id-mapeo/modules/svg/vertices'>;
}
declare module 'id-mapeo/modules/ui/account.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/account'>;
}
declare module 'id-mapeo/modules/ui/attribution.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/attribution'>;
}
declare module 'id-mapeo/modules/ui/background_display_options.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/background_display_options'>;
}
declare module 'id-mapeo/modules/ui/background_offset.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/background_offset'>;
}
declare module 'id-mapeo/modules/ui/background.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/background'>;
}
declare module 'id-mapeo/modules/ui/changeset_editor.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/changeset_editor'>;
}
declare module 'id-mapeo/modules/ui/cmd.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/cmd'>;
}
declare module 'id-mapeo/modules/ui/combobox.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/combobox'>;
}
declare module 'id-mapeo/modules/ui/commit_changes.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/commit_changes'>;
}
declare module 'id-mapeo/modules/ui/commit_warnings.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/commit_warnings'>;
}
declare module 'id-mapeo/modules/ui/commit.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/commit'>;
}
declare module 'id-mapeo/modules/ui/confirm.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/confirm'>;
}
declare module 'id-mapeo/modules/ui/conflicts.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/conflicts'>;
}
declare module 'id-mapeo/modules/ui/contributors.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/contributors'>;
}
declare module 'id-mapeo/modules/ui/curtain.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/curtain'>;
}
declare module 'id-mapeo/modules/ui/data_editor.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/data_editor'>;
}
declare module 'id-mapeo/modules/ui/data_header.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/data_header'>;
}
declare module 'id-mapeo/modules/ui/disclosure.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/disclosure'>;
}
declare module 'id-mapeo/modules/ui/edit_menu.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/edit_menu'>;
}
declare module 'id-mapeo/modules/ui/entity_editor.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/entity_editor'>;
}
declare module 'id-mapeo/modules/ui/entity_issues.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/entity_issues'>;
}
declare module 'id-mapeo/modules/ui/feature_info.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/feature_info'>;
}
declare module 'id-mapeo/modules/ui/feature_list.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/feature_list'>;
}
declare module 'id-mapeo/modules/ui/field_help.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/field_help'>;
}
declare module 'id-mapeo/modules/ui/field.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/field'>;
}
declare module 'id-mapeo/modules/ui/fields/access.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields/access'>;
}
declare module 'id-mapeo/modules/ui/fields/address.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields/address'>;
}
declare module 'id-mapeo/modules/ui/fields/check.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields/check'>;
}
declare module 'id-mapeo/modules/ui/fields/combo.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields/combo'>;
}
declare module 'id-mapeo/modules/ui/fields/cycleway.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields/cycleway'>;
}
declare module 'id-mapeo/modules/ui/fields/index' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields'>;
}
declare module 'id-mapeo/modules/ui/fields/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields'>;
}
declare module 'id-mapeo/modules/ui/fields/input.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields/input'>;
}
declare module 'id-mapeo/modules/ui/fields/lanes.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields/lanes'>;
}
declare module 'id-mapeo/modules/ui/fields/localized.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields/localized'>;
}
declare module 'id-mapeo/modules/ui/fields/maxspeed.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields/maxspeed'>;
}
declare module 'id-mapeo/modules/ui/fields/radio.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields/radio'>;
}
declare module 'id-mapeo/modules/ui/fields/restrictions.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields/restrictions'>;
}
declare module 'id-mapeo/modules/ui/fields/textarea.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields/textarea'>;
}
declare module 'id-mapeo/modules/ui/fields/wikidata.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields/wikidata'>;
}
declare module 'id-mapeo/modules/ui/fields/wikipedia.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/fields/wikipedia'>;
}
declare module 'id-mapeo/modules/ui/flash.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/flash'>;
}
declare module 'id-mapeo/modules/ui/form_fields.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/form_fields'>;
}
declare module 'id-mapeo/modules/ui/full_screen.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/full_screen'>;
}
declare module 'id-mapeo/modules/ui/geolocate.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/geolocate'>;
}
declare module 'id-mapeo/modules/ui/help.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/help'>;
}
declare module 'id-mapeo/modules/ui/improveOSM_comments.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/improveOSM_comments'>;
}
declare module 'id-mapeo/modules/ui/improveOSM_details.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/improveOSM_details'>;
}
declare module 'id-mapeo/modules/ui/improveOSM_editor.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/improveOSM_editor'>;
}
declare module 'id-mapeo/modules/ui/improveOSM_header.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/improveOSM_header'>;
}
declare module 'id-mapeo/modules/ui/index' {
  declare module.exports: $Exports<'id-mapeo/modules/ui'>;
}
declare module 'id-mapeo/modules/ui/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui'>;
}
declare module 'id-mapeo/modules/ui/info.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/info'>;
}
declare module 'id-mapeo/modules/ui/init.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/init'>;
}
declare module 'id-mapeo/modules/ui/inspector.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/inspector'>;
}
declare module 'id-mapeo/modules/ui/intro/area.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/intro/area'>;
}
declare module 'id-mapeo/modules/ui/intro/building.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/intro/building'>;
}
declare module 'id-mapeo/modules/ui/intro/helper.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/intro/helper'>;
}
declare module 'id-mapeo/modules/ui/intro/index' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/intro'>;
}
declare module 'id-mapeo/modules/ui/intro/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/intro'>;
}
declare module 'id-mapeo/modules/ui/intro/intro.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/intro/intro'>;
}
declare module 'id-mapeo/modules/ui/intro/line.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/intro/line'>;
}
declare module 'id-mapeo/modules/ui/intro/navigation.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/intro/navigation'>;
}
declare module 'id-mapeo/modules/ui/intro/point.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/intro/point'>;
}
declare module 'id-mapeo/modules/ui/intro/start_editing.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/intro/start_editing'>;
}
declare module 'id-mapeo/modules/ui/intro/welcome.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/intro/welcome'>;
}
declare module 'id-mapeo/modules/ui/issues.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/issues'>;
}
declare module 'id-mapeo/modules/ui/keepRight_details.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/keepRight_details'>;
}
declare module 'id-mapeo/modules/ui/keepRight_editor.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/keepRight_editor'>;
}
declare module 'id-mapeo/modules/ui/keepRight_header.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/keepRight_header'>;
}
declare module 'id-mapeo/modules/ui/lasso.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/lasso'>;
}
declare module 'id-mapeo/modules/ui/loading.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/loading'>;
}
declare module 'id-mapeo/modules/ui/map_data.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/map_data'>;
}
declare module 'id-mapeo/modules/ui/map_in_map.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/map_in_map'>;
}
declare module 'id-mapeo/modules/ui/modal.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/modal'>;
}
declare module 'id-mapeo/modules/ui/note_comments.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/note_comments'>;
}
declare module 'id-mapeo/modules/ui/note_editor.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/note_editor'>;
}
declare module 'id-mapeo/modules/ui/note_header.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/note_header'>;
}
declare module 'id-mapeo/modules/ui/note_report.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/note_report'>;
}
declare module 'id-mapeo/modules/ui/notice.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/notice'>;
}
declare module 'id-mapeo/modules/ui/panels/background.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/panels/background'>;
}
declare module 'id-mapeo/modules/ui/panels/history.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/panels/history'>;
}
declare module 'id-mapeo/modules/ui/panels/index' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/panels'>;
}
declare module 'id-mapeo/modules/ui/panels/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/panels'>;
}
declare module 'id-mapeo/modules/ui/panels/location.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/panels/location'>;
}
declare module 'id-mapeo/modules/ui/panels/measurement.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/panels/measurement'>;
}
declare module 'id-mapeo/modules/ui/photoviewer.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/photoviewer'>;
}
declare module 'id-mapeo/modules/ui/preset_editor.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/preset_editor'>;
}
declare module 'id-mapeo/modules/ui/preset_favorite_button.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/preset_favorite_button'>;
}
declare module 'id-mapeo/modules/ui/preset_icon.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/preset_icon'>;
}
declare module 'id-mapeo/modules/ui/preset_list.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/preset_list'>;
}
declare module 'id-mapeo/modules/ui/quick_links.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/quick_links'>;
}
declare module 'id-mapeo/modules/ui/radial_menu.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/radial_menu'>;
}
declare module 'id-mapeo/modules/ui/raw_member_editor.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/raw_member_editor'>;
}
declare module 'id-mapeo/modules/ui/raw_membership_editor.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/raw_membership_editor'>;
}
declare module 'id-mapeo/modules/ui/raw_tag_editor.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/raw_tag_editor'>;
}
declare module 'id-mapeo/modules/ui/restore.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/restore'>;
}
declare module 'id-mapeo/modules/ui/scale.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/scale'>;
}
declare module 'id-mapeo/modules/ui/selection_list.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/selection_list'>;
}
declare module 'id-mapeo/modules/ui/settings/custom_background.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/settings/custom_background'>;
}
declare module 'id-mapeo/modules/ui/settings/custom_data.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/settings/custom_data'>;
}
declare module 'id-mapeo/modules/ui/settings/index' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/settings'>;
}
declare module 'id-mapeo/modules/ui/settings/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/settings'>;
}
declare module 'id-mapeo/modules/ui/shortcuts.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/shortcuts'>;
}
declare module 'id-mapeo/modules/ui/sidebar.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/sidebar'>;
}
declare module 'id-mapeo/modules/ui/source_switch.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/source_switch'>;
}
declare module 'id-mapeo/modules/ui/spinner.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/spinner'>;
}
declare module 'id-mapeo/modules/ui/splash.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/splash'>;
}
declare module 'id-mapeo/modules/ui/status.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/status'>;
}
declare module 'id-mapeo/modules/ui/success.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/success'>;
}
declare module 'id-mapeo/modules/ui/tag_reference.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/tag_reference'>;
}
declare module 'id-mapeo/modules/ui/toggle.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/toggle'>;
}
declare module 'id-mapeo/modules/ui/tools/add_favorite.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/tools/add_favorite'>;
}
declare module 'id-mapeo/modules/ui/tools/add_recent.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/tools/add_recent'>;
}
declare module 'id-mapeo/modules/ui/tools/index' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/tools'>;
}
declare module 'id-mapeo/modules/ui/tools/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/tools'>;
}
declare module 'id-mapeo/modules/ui/tools/modes.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/tools/modes'>;
}
declare module 'id-mapeo/modules/ui/tools/notes.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/tools/notes'>;
}
declare module 'id-mapeo/modules/ui/tools/save.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/tools/save'>;
}
declare module 'id-mapeo/modules/ui/tools/search_add.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/tools/search_add'>;
}
declare module 'id-mapeo/modules/ui/tools/sidebar_toggle.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/tools/sidebar_toggle'>;
}
declare module 'id-mapeo/modules/ui/tools/undo_redo.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/tools/undo_redo'>;
}
declare module 'id-mapeo/modules/ui/tooltipHtml.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/tooltipHtml'>;
}
declare module 'id-mapeo/modules/ui/top_toolbar.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/top_toolbar'>;
}
declare module 'id-mapeo/modules/ui/version.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/version'>;
}
declare module 'id-mapeo/modules/ui/view_on_keepRight.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/view_on_keepRight'>;
}
declare module 'id-mapeo/modules/ui/view_on_osm.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/view_on_osm'>;
}
declare module 'id-mapeo/modules/ui/zoom.js' {
  declare module.exports: $Exports<'id-mapeo/modules/ui/zoom'>;
}
declare module 'id-mapeo/modules/util/array.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/array'>;
}
declare module 'id-mapeo/modules/util/bind_once.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/bind_once'>;
}
declare module 'id-mapeo/modules/util/clean_tags.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/clean_tags'>;
}
declare module 'id-mapeo/modules/util/detect.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/detect'>;
}
declare module 'id-mapeo/modules/util/dimensions.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/dimensions'>;
}
declare module 'id-mapeo/modules/util/get_set_value.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/get_set_value'>;
}
declare module 'id-mapeo/modules/util/index' {
  declare module.exports: $Exports<'id-mapeo/modules/util'>;
}
declare module 'id-mapeo/modules/util/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util'>;
}
declare module 'id-mapeo/modules/util/jsonp_request.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/jsonp_request'>;
}
declare module 'id-mapeo/modules/util/jxon.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/jxon'>;
}
declare module 'id-mapeo/modules/util/keybinding.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/keybinding'>;
}
declare module 'id-mapeo/modules/util/locale.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/locale'>;
}
declare module 'id-mapeo/modules/util/object.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/object'>;
}
declare module 'id-mapeo/modules/util/rebind.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/rebind'>;
}
declare module 'id-mapeo/modules/util/session_mutex.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/session_mutex'>;
}
declare module 'id-mapeo/modules/util/svg_paths_rtl_fix.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/svg_paths_rtl_fix'>;
}
declare module 'id-mapeo/modules/util/tiler.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/tiler'>;
}
declare module 'id-mapeo/modules/util/tooltip.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/tooltip'>;
}
declare module 'id-mapeo/modules/util/trigger_event.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/trigger_event'>;
}
declare module 'id-mapeo/modules/util/units.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/units'>;
}
declare module 'id-mapeo/modules/util/util.js' {
  declare module.exports: $Exports<'id-mapeo/modules/util/util'>;
}
declare module 'id-mapeo/modules/validations/almost_junction.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/almost_junction'>;
}
declare module 'id-mapeo/modules/validations/close_nodes.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/close_nodes'>;
}
declare module 'id-mapeo/modules/validations/crossing_ways.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/crossing_ways'>;
}
declare module 'id-mapeo/modules/validations/disconnected_way.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/disconnected_way'>;
}
declare module 'id-mapeo/modules/validations/fixme_tag.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/fixme_tag'>;
}
declare module 'id-mapeo/modules/validations/generic_name.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/generic_name'>;
}
declare module 'id-mapeo/modules/validations/impossible_oneway.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/impossible_oneway'>;
}
declare module 'id-mapeo/modules/validations/incompatible_source.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/incompatible_source'>;
}
declare module 'id-mapeo/modules/validations/index' {
  declare module.exports: $Exports<'id-mapeo/modules/validations'>;
}
declare module 'id-mapeo/modules/validations/index.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations'>;
}
declare module 'id-mapeo/modules/validations/invalid_format.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/invalid_format'>;
}
declare module 'id-mapeo/modules/validations/maprules.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/maprules'>;
}
declare module 'id-mapeo/modules/validations/missing_role.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/missing_role'>;
}
declare module 'id-mapeo/modules/validations/missing_tag.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/missing_tag'>;
}
declare module 'id-mapeo/modules/validations/outdated_tags.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/outdated_tags'>;
}
declare module 'id-mapeo/modules/validations/private_data.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/private_data'>;
}
declare module 'id-mapeo/modules/validations/tag_suggests_area.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/tag_suggests_area'>;
}
declare module 'id-mapeo/modules/validations/unsquare_way.js' {
  declare module.exports: $Exports<'id-mapeo/modules/validations/unsquare_way'>;
}
declare module 'id-mapeo/monkey_patches/patch-locales.js' {
  declare module.exports: $Exports<'id-mapeo/monkey_patches/patch-locales'>;
}
