// flow-typed signature: 625bd6da85e0a8e0549656227d20e66e
// flow-typed version: <<STUB>>/insert-css_v^2.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'insert-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'insert-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'insert-css/example' {
  declare module.exports: any;
}

declare module 'insert-css/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'insert-css/example.js' {
  declare module.exports: $Exports<'insert-css/example'>;
}
declare module 'insert-css/index' {
  declare module.exports: $Exports<'insert-css'>;
}
declare module 'insert-css/index.js' {
  declare module.exports: $Exports<'insert-css'>;
}
declare module 'insert-css/test.js' {
  declare module.exports: $Exports<'insert-css/test'>;
}
