// flow-typed signature: b304683eb77e01aba621a66e6b6d0a39
// flow-typed version: <<STUB>>/kappa-core_v^4.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kappa-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kappa-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kappa-core/example' {
  declare module.exports: any;
}

declare module 'kappa-core/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kappa-core/example.js' {
  declare module.exports: $Exports<'kappa-core/example'>;
}
declare module 'kappa-core/index' {
  declare module.exports: $Exports<'kappa-core'>;
}
declare module 'kappa-core/index.js' {
  declare module.exports: $Exports<'kappa-core'>;
}
declare module 'kappa-core/test/basic.js' {
  declare module.exports: $Exports<'kappa-core/test/basic'>;
}
