// flow-typed signature: 7770dddf3bc5b17890e5878143712d75
// flow-typed version: <<STUB>>/kappa-osm_v^3.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kappa-osm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kappa-osm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kappa-osm/lib/bkd-index' {
  declare module.exports: any;
}

declare module 'kappa-osm/lib/changeset-index' {
  declare module.exports: any;
}

declare module 'kappa-osm/lib/check-element' {
  declare module.exports: any;
}

declare module 'kappa-osm/lib/history-index' {
  declare module.exports: any;
}

declare module 'kappa-osm/lib/kv-index' {
  declare module.exports: any;
}

declare module 'kappa-osm/lib/refs-index' {
  declare module.exports: any;
}

declare module 'kappa-osm/lib/types-index' {
  declare module.exports: any;
}

declare module 'kappa-osm/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kappa-osm/index' {
  declare module.exports: $Exports<'kappa-osm'>;
}
declare module 'kappa-osm/index.js' {
  declare module.exports: $Exports<'kappa-osm'>;
}
declare module 'kappa-osm/lib/bkd-index.js' {
  declare module.exports: $Exports<'kappa-osm/lib/bkd-index'>;
}
declare module 'kappa-osm/lib/changeset-index.js' {
  declare module.exports: $Exports<'kappa-osm/lib/changeset-index'>;
}
declare module 'kappa-osm/lib/check-element.js' {
  declare module.exports: $Exports<'kappa-osm/lib/check-element'>;
}
declare module 'kappa-osm/lib/history-index.js' {
  declare module.exports: $Exports<'kappa-osm/lib/history-index'>;
}
declare module 'kappa-osm/lib/kv-index.js' {
  declare module.exports: $Exports<'kappa-osm/lib/kv-index'>;
}
declare module 'kappa-osm/lib/refs-index.js' {
  declare module.exports: $Exports<'kappa-osm/lib/refs-index'>;
}
declare module 'kappa-osm/lib/types-index.js' {
  declare module.exports: $Exports<'kappa-osm/lib/types-index'>;
}
declare module 'kappa-osm/lib/utils.js' {
  declare module.exports: $Exports<'kappa-osm/lib/utils'>;
}
