// flow-typed signature: cb3cc81b1fe338d72d117259c8ccc9c8
// flow-typed version: <<STUB>>/ky_v^0.14.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ky' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ky/umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ky/index' {
  declare module.exports: $Exports<'ky'>;
}
declare module 'ky/index.js' {
  declare module.exports: $Exports<'ky'>;
}
declare module 'ky/umd.js' {
  declare module.exports: $Exports<'ky/umd'>;
}
