// flow-typed signature: f16247cd43aa71d6d6dc62c396cc8a7a
// flow-typed version: <<STUB>>/level_v^5.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'level'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'level' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'level/browser' {
  declare module.exports: any;
}

declare module 'level/level' {
  declare module.exports: any;
}

declare module 'level/test-browser' {
  declare module.exports: any;
}

declare module 'level/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'level/browser.js' {
  declare module.exports: $Exports<'level/browser'>;
}
declare module 'level/level.js' {
  declare module.exports: $Exports<'level/level'>;
}
declare module 'level/test-browser.js' {
  declare module.exports: $Exports<'level/test-browser'>;
}
declare module 'level/test.js' {
  declare module.exports: $Exports<'level/test'>;
}
