// flow-typed signature: 4520ab57a4854cec5389be582c8fae91
// flow-typed version: <<STUB>>/license-check_v^1.1.5/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'license-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'license-check' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'license-check/bin/server' {
  declare module.exports: any;
}

declare module 'license-check/test/fixture/ko' {
  declare module.exports: any;
}

declare module 'license-check/test/fixture/ok' {
  declare module.exports: any;
}

declare module 'license-check/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'license-check/bin/server.js' {
  declare module.exports: $Exports<'license-check/bin/server'>;
}
declare module 'license-check/index' {
  declare module.exports: $Exports<'license-check'>;
}
declare module 'license-check/index.js' {
  declare module.exports: $Exports<'license-check'>;
}
declare module 'license-check/test/fixture/ko.js' {
  declare module.exports: $Exports<'license-check/test/fixture/ko'>;
}
declare module 'license-check/test/fixture/ok.js' {
  declare module.exports: $Exports<'license-check/test/fixture/ok'>;
}
declare module 'license-check/test/test.js' {
  declare module.exports: $Exports<'license-check/test/test'>;
}
