// flow-typed signature: 3143d19ef1151047a4435e52564fd055
// flow-typed version: <<STUB>>/mapeo-styles_v^3.0.2/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mapeo-styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mapeo-styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mapeo-styles/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mapeo-styles/index' {
  declare module.exports: $Exports<'mapeo-styles'>;
}
declare module 'mapeo-styles/index.js' {
  declare module.exports: $Exports<'mapeo-styles'>;
}
declare module 'mapeo-styles/test/basic.js' {
  declare module.exports: $Exports<'mapeo-styles/test/basic'>;
}
