// flow-typed signature: b2a5baa910c90717d63802f575ba3d14
// flow-typed version: <<STUB>>/mapeo-entity-filter_v^2.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mapeo-entity-filter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mapeo-entity-filter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mapeo-entity-filter/bench/bench' {
  declare module.exports: any;
}

declare module 'mapeo-entity-filter/bench/big' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mapeo-entity-filter/bench/bench.js' {
  declare module.exports: $Exports<'mapeo-entity-filter/bench/bench'>;
}
declare module 'mapeo-entity-filter/bench/big.js' {
  declare module.exports: $Exports<'mapeo-entity-filter/bench/big'>;
}
declare module 'mapeo-entity-filter/index' {
  declare module.exports: $Exports<'mapeo-entity-filter'>;
}
declare module 'mapeo-entity-filter/index.js' {
  declare module.exports: $Exports<'mapeo-entity-filter'>;
}
