// flow-typed signature: 86c2d92f5f315177e1ef3f4af0ec3f93
// flow-typed version: <<STUB>>/mapeo-server_v^17.0.6/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mapeo-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mapeo-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mapeo-server/api' {
  declare module.exports: any;
}

declare module 'mapeo-server/server' {
  declare module.exports: any;
}

declare module 'mapeo-server/test/device' {
  declare module.exports: any;
}

declare module 'mapeo-server/test/fileSync' {
  declare module.exports: any;
}

declare module 'mapeo-server/test/media' {
  declare module.exports: any;
}

declare module 'mapeo-server/test/observations' {
  declare module.exports: any;
}

declare module 'mapeo-server/test/presets' {
  declare module.exports: any;
}

declare module 'mapeo-server/test/server' {
  declare module.exports: any;
}

declare module 'mapeo-server/test/styles' {
  declare module.exports: any;
}

declare module 'mapeo-server/test/sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mapeo-server/api.js' {
  declare module.exports: $Exports<'mapeo-server/api'>;
}
declare module 'mapeo-server/index' {
  declare module.exports: $Exports<'mapeo-server'>;
}
declare module 'mapeo-server/index.js' {
  declare module.exports: $Exports<'mapeo-server'>;
}
declare module 'mapeo-server/server.js' {
  declare module.exports: $Exports<'mapeo-server/server'>;
}
declare module 'mapeo-server/test/device.js' {
  declare module.exports: $Exports<'mapeo-server/test/device'>;
}
declare module 'mapeo-server/test/fileSync.js' {
  declare module.exports: $Exports<'mapeo-server/test/fileSync'>;
}
declare module 'mapeo-server/test/media.js' {
  declare module.exports: $Exports<'mapeo-server/test/media'>;
}
declare module 'mapeo-server/test/observations.js' {
  declare module.exports: $Exports<'mapeo-server/test/observations'>;
}
declare module 'mapeo-server/test/presets.js' {
  declare module.exports: $Exports<'mapeo-server/test/presets'>;
}
declare module 'mapeo-server/test/server.js' {
  declare module.exports: $Exports<'mapeo-server/test/server'>;
}
declare module 'mapeo-server/test/styles.js' {
  declare module.exports: $Exports<'mapeo-server/test/styles'>;
}
declare module 'mapeo-server/test/sync.js' {
  declare module.exports: $Exports<'mapeo-server/test/sync'>;
}
