// flow-typed signature: a765c00092a70e069df30233e3820b84
// flow-typed version: <<STUB>>/mock-data_v^1.5.5/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-data'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-data' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-data/lib/boolean' {
  declare module.exports: any;
}

declare module 'mock-data/lib/date' {
  declare module.exports: any;
}

declare module 'mock-data/lib/integer' {
  declare module.exports: any;
}

declare module 'mock-data/lib/ipv4' {
  declare module.exports: any;
}

declare module 'mock-data/lib/string' {
  declare module.exports: any;
}

declare module 'mock-data/test' {
  declare module.exports: any;
}

declare module 'mock-data/tests/lib/test-boolean' {
  declare module.exports: any;
}

declare module 'mock-data/tests/lib/test-date' {
  declare module.exports: any;
}

declare module 'mock-data/tests/lib/test-integer' {
  declare module.exports: any;
}

declare module 'mock-data/tests/lib/test-ipv4' {
  declare module.exports: any;
}

declare module 'mock-data/tests/lib/test-string' {
  declare module.exports: any;
}

declare module 'mock-data/tests/util/test-generator' {
  declare module.exports: any;
}

declare module 'mock-data/tests/util/test-utils' {
  declare module.exports: any;
}

declare module 'mock-data/util/generator' {
  declare module.exports: any;
}

declare module 'mock-data/util/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-data/index' {
  declare module.exports: $Exports<'mock-data'>;
}
declare module 'mock-data/index.js' {
  declare module.exports: $Exports<'mock-data'>;
}
declare module 'mock-data/lib/boolean.js' {
  declare module.exports: $Exports<'mock-data/lib/boolean'>;
}
declare module 'mock-data/lib/date.js' {
  declare module.exports: $Exports<'mock-data/lib/date'>;
}
declare module 'mock-data/lib/integer.js' {
  declare module.exports: $Exports<'mock-data/lib/integer'>;
}
declare module 'mock-data/lib/ipv4.js' {
  declare module.exports: $Exports<'mock-data/lib/ipv4'>;
}
declare module 'mock-data/lib/string.js' {
  declare module.exports: $Exports<'mock-data/lib/string'>;
}
declare module 'mock-data/test.js' {
  declare module.exports: $Exports<'mock-data/test'>;
}
declare module 'mock-data/tests/lib/test-boolean.js' {
  declare module.exports: $Exports<'mock-data/tests/lib/test-boolean'>;
}
declare module 'mock-data/tests/lib/test-date.js' {
  declare module.exports: $Exports<'mock-data/tests/lib/test-date'>;
}
declare module 'mock-data/tests/lib/test-integer.js' {
  declare module.exports: $Exports<'mock-data/tests/lib/test-integer'>;
}
declare module 'mock-data/tests/lib/test-ipv4.js' {
  declare module.exports: $Exports<'mock-data/tests/lib/test-ipv4'>;
}
declare module 'mock-data/tests/lib/test-string.js' {
  declare module.exports: $Exports<'mock-data/tests/lib/test-string'>;
}
declare module 'mock-data/tests/util/test-generator.js' {
  declare module.exports: $Exports<'mock-data/tests/util/test-generator'>;
}
declare module 'mock-data/tests/util/test-utils.js' {
  declare module.exports: $Exports<'mock-data/tests/util/test-utils'>;
}
declare module 'mock-data/util/generator.js' {
  declare module.exports: $Exports<'mock-data/util/generator'>;
}
declare module 'mock-data/util/utils.js' {
  declare module.exports: $Exports<'mock-data/util/utils'>;
}
