// flow-typed signature: 0dd2ec2662cf4192908374badb436cb4
// flow-typed version: <<STUB>>/network-speed_vgithub:okdistribute/network-speed/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'network-speed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'network-speed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'network-speed/app' {
  declare module.exports: any;
}

declare module 'network-speed/dist/module' {
  declare module.exports: any;
}

declare module 'network-speed/test_usage' {
  declare module.exports: any;
}

declare module 'network-speed/test/test' {
  declare module.exports: any;
}

declare module 'network-speed/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'network-speed/app.js' {
  declare module.exports: $Exports<'network-speed/app'>;
}
declare module 'network-speed/dist/module.js' {
  declare module.exports: $Exports<'network-speed/dist/module'>;
}
declare module 'network-speed/test_usage.js' {
  declare module.exports: $Exports<'network-speed/test_usage'>;
}
declare module 'network-speed/test/test.js' {
  declare module.exports: $Exports<'network-speed/test/test'>;
}
declare module 'network-speed/webpack.config.js' {
  declare module.exports: $Exports<'network-speed/webpack.config'>;
}
