// flow-typed signature: 6ca3955ab1d24963466e73556fe4b02d
// flow-typed version: <<STUB>>/node-wifi_v^2.0.12/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-wifi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-wifi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-wifi/bin/wifi' {
  declare module.exports: any;
}

declare module 'node-wifi/commitlint.config' {
  declare module.exports: any;
}

declare module 'node-wifi/src/env' {
  declare module.exports: any;
}

declare module 'node-wifi/src/linux-connect' {
  declare module.exports: any;
}

declare module 'node-wifi/src/linux-current-connections' {
  declare module.exports: any;
}

declare module 'node-wifi/src/linux-delete' {
  declare module.exports: any;
}

declare module 'node-wifi/src/linux-disconnect' {
  declare module.exports: any;
}

declare module 'node-wifi/src/linux-scan' {
  declare module.exports: any;
}

declare module 'node-wifi/src/mac-connect' {
  declare module.exports: any;
}

declare module 'node-wifi/src/mac-current-connections' {
  declare module.exports: any;
}

declare module 'node-wifi/src/mac-delete' {
  declare module.exports: any;
}

declare module 'node-wifi/src/mac-scan' {
  declare module.exports: any;
}

declare module 'node-wifi/src/network-utils' {
  declare module.exports: any;
}

declare module 'node-wifi/src/wifi' {
  declare module.exports: any;
}

declare module 'node-wifi/src/windows-connect' {
  declare module.exports: any;
}

declare module 'node-wifi/src/windows-current-connections' {
  declare module.exports: any;
}

declare module 'node-wifi/src/windows-disconnect' {
  declare module.exports: any;
}

declare module 'node-wifi/src/windows-scan' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-wifi/bin/wifi.js' {
  declare module.exports: $Exports<'node-wifi/bin/wifi'>;
}
declare module 'node-wifi/commitlint.config.js' {
  declare module.exports: $Exports<'node-wifi/commitlint.config'>;
}
declare module 'node-wifi/src/env.js' {
  declare module.exports: $Exports<'node-wifi/src/env'>;
}
declare module 'node-wifi/src/linux-connect.js' {
  declare module.exports: $Exports<'node-wifi/src/linux-connect'>;
}
declare module 'node-wifi/src/linux-current-connections.js' {
  declare module.exports: $Exports<'node-wifi/src/linux-current-connections'>;
}
declare module 'node-wifi/src/linux-delete.js' {
  declare module.exports: $Exports<'node-wifi/src/linux-delete'>;
}
declare module 'node-wifi/src/linux-disconnect.js' {
  declare module.exports: $Exports<'node-wifi/src/linux-disconnect'>;
}
declare module 'node-wifi/src/linux-scan.js' {
  declare module.exports: $Exports<'node-wifi/src/linux-scan'>;
}
declare module 'node-wifi/src/mac-connect.js' {
  declare module.exports: $Exports<'node-wifi/src/mac-connect'>;
}
declare module 'node-wifi/src/mac-current-connections.js' {
  declare module.exports: $Exports<'node-wifi/src/mac-current-connections'>;
}
declare module 'node-wifi/src/mac-delete.js' {
  declare module.exports: $Exports<'node-wifi/src/mac-delete'>;
}
declare module 'node-wifi/src/mac-scan.js' {
  declare module.exports: $Exports<'node-wifi/src/mac-scan'>;
}
declare module 'node-wifi/src/network-utils.js' {
  declare module.exports: $Exports<'node-wifi/src/network-utils'>;
}
declare module 'node-wifi/src/wifi.js' {
  declare module.exports: $Exports<'node-wifi/src/wifi'>;
}
declare module 'node-wifi/src/windows-connect.js' {
  declare module.exports: $Exports<'node-wifi/src/windows-connect'>;
}
declare module 'node-wifi/src/windows-current-connections.js' {
  declare module.exports: $Exports<'node-wifi/src/windows-current-connections'>;
}
declare module 'node-wifi/src/windows-disconnect.js' {
  declare module.exports: $Exports<'node-wifi/src/windows-disconnect'>;
}
declare module 'node-wifi/src/windows-scan.js' {
  declare module.exports: $Exports<'node-wifi/src/windows-scan'>;
}
