// flow-typed signature: 5259f112041ea8f5290bd8bf7949f968
// flow-typed version: <<STUB>>/object-path-immutable_v^4.1.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-path-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-path-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object-path-immutable/cjs/object-path-immutable' {
  declare module.exports: any;
}

declare module 'object-path-immutable/esm/object-path-immutable' {
  declare module.exports: any;
}

declare module 'object-path-immutable/rollup.config' {
  declare module.exports: any;
}

declare module 'object-path-immutable/src/object-path-immutable' {
  declare module.exports: any;
}

declare module 'object-path-immutable/test/test' {
  declare module.exports: any;
}

declare module 'object-path-immutable/umd/object-path-immutable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object-path-immutable/cjs/object-path-immutable.js' {
  declare module.exports: $Exports<'object-path-immutable/cjs/object-path-immutable'>;
}
declare module 'object-path-immutable/esm/object-path-immutable.js' {
  declare module.exports: $Exports<'object-path-immutable/esm/object-path-immutable'>;
}
declare module 'object-path-immutable/rollup.config.js' {
  declare module.exports: $Exports<'object-path-immutable/rollup.config'>;
}
declare module 'object-path-immutable/src/object-path-immutable.js' {
  declare module.exports: $Exports<'object-path-immutable/src/object-path-immutable'>;
}
declare module 'object-path-immutable/test/test.js' {
  declare module.exports: $Exports<'object-path-immutable/test/test'>;
}
declare module 'object-path-immutable/umd/object-path-immutable.js' {
  declare module.exports: $Exports<'object-path-immutable/umd/object-path-immutable'>;
}
