// flow-typed signature: 57615dc705c7d728ddcd3fc792a9c6f8
// flow-typed version: <<STUB>>/once_v^1.4.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'once'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'once' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'once/once' {
  declare module.exports: any;
}

// Filename aliases
declare module 'once/once.js' {
  declare module.exports: $Exports<'once/once'>;
}
