// flow-typed signature: cc78f3f6cb9cc35acf10f6518c00b4cf
// flow-typed version: <<STUB>>/osm-p2p_v^5.1.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'osm-p2p'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'osm-p2p' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'osm-p2p/index' {
  declare module.exports: $Exports<'osm-p2p'>;
}
declare module 'osm-p2p/index.js' {
  declare module.exports: $Exports<'osm-p2p'>;
}
