// flow-typed signature: 11892f26cb23616a10f5d8e1d9cd678a
// flow-typed version: <<STUB>>/osm-p2p-server_vv6.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'osm-p2p-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'osm-p2p-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'osm-p2p-server/api/close_changeset' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/api/create_changeset' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/api/create_element' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/api/get_changes' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/api/get_element' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/api/get_map' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/api' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/api/put_changes' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/bin/cmd' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/errors' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/example/express' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/example/server' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/lib/check_ref_ex' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/lib/filter_deletes' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/lib/h' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/lib/obj2osm' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/lib/osm2obj' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/lib/replace_ids' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/lib/util' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/lib/validate_changeset' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/routes/changeset_close' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/routes/changeset_create' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/routes/changeset_download' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/routes/changeset_upload' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/routes/changesets' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/routes/element_create' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/routes/element_delete' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/routes/element_history' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/routes/element_multi_fetch' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/routes/element_read' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/routes/element_version' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/routes' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/routes/misc_capabilities' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/routes/misc_map' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/api/close_changeset.test' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/api/create_changeset.test' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/api/create_element.test' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/api/get_changes.test' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/api/get_element.test' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/api/get_map.test' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/bbox_order' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/bbox' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/capabilities' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/changeset_delete' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/changeset_placeholder' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/changeset_upload_observation' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/changeset_upload_relation' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/changeset_upload' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/changeset' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/delete' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/get_map' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/ghost_points' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/history' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/lib/filter_deletes.test' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/lib/replace_ids.test' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/lib/slowdb' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/lib/test_db' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/lib/test_server' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/lib/util' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/lib/validate_changeset.test' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/malformed_changeset' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/many_types' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/multi_fetch' {
  declare module.exports: any;
}

declare module 'osm-p2p-server/test/split_delete_way' {
  declare module.exports: any;
}

// Filename aliases
declare module 'osm-p2p-server/api/close_changeset.js' {
  declare module.exports: $Exports<'osm-p2p-server/api/close_changeset'>;
}
declare module 'osm-p2p-server/api/create_changeset.js' {
  declare module.exports: $Exports<'osm-p2p-server/api/create_changeset'>;
}
declare module 'osm-p2p-server/api/create_element.js' {
  declare module.exports: $Exports<'osm-p2p-server/api/create_element'>;
}
declare module 'osm-p2p-server/api/get_changes.js' {
  declare module.exports: $Exports<'osm-p2p-server/api/get_changes'>;
}
declare module 'osm-p2p-server/api/get_element.js' {
  declare module.exports: $Exports<'osm-p2p-server/api/get_element'>;
}
declare module 'osm-p2p-server/api/get_map.js' {
  declare module.exports: $Exports<'osm-p2p-server/api/get_map'>;
}
declare module 'osm-p2p-server/api/index' {
  declare module.exports: $Exports<'osm-p2p-server/api'>;
}
declare module 'osm-p2p-server/api/index.js' {
  declare module.exports: $Exports<'osm-p2p-server/api'>;
}
declare module 'osm-p2p-server/api/put_changes.js' {
  declare module.exports: $Exports<'osm-p2p-server/api/put_changes'>;
}
declare module 'osm-p2p-server/bin/cmd.js' {
  declare module.exports: $Exports<'osm-p2p-server/bin/cmd'>;
}
declare module 'osm-p2p-server/errors/index' {
  declare module.exports: $Exports<'osm-p2p-server/errors'>;
}
declare module 'osm-p2p-server/errors/index.js' {
  declare module.exports: $Exports<'osm-p2p-server/errors'>;
}
declare module 'osm-p2p-server/example/express.js' {
  declare module.exports: $Exports<'osm-p2p-server/example/express'>;
}
declare module 'osm-p2p-server/example/server.js' {
  declare module.exports: $Exports<'osm-p2p-server/example/server'>;
}
declare module 'osm-p2p-server/index' {
  declare module.exports: $Exports<'osm-p2p-server'>;
}
declare module 'osm-p2p-server/index.js' {
  declare module.exports: $Exports<'osm-p2p-server'>;
}
declare module 'osm-p2p-server/lib/check_ref_ex.js' {
  declare module.exports: $Exports<'osm-p2p-server/lib/check_ref_ex'>;
}
declare module 'osm-p2p-server/lib/filter_deletes.js' {
  declare module.exports: $Exports<'osm-p2p-server/lib/filter_deletes'>;
}
declare module 'osm-p2p-server/lib/h.js' {
  declare module.exports: $Exports<'osm-p2p-server/lib/h'>;
}
declare module 'osm-p2p-server/lib/obj2osm.js' {
  declare module.exports: $Exports<'osm-p2p-server/lib/obj2osm'>;
}
declare module 'osm-p2p-server/lib/osm2obj.js' {
  declare module.exports: $Exports<'osm-p2p-server/lib/osm2obj'>;
}
declare module 'osm-p2p-server/lib/replace_ids.js' {
  declare module.exports: $Exports<'osm-p2p-server/lib/replace_ids'>;
}
declare module 'osm-p2p-server/lib/util.js' {
  declare module.exports: $Exports<'osm-p2p-server/lib/util'>;
}
declare module 'osm-p2p-server/lib/validate_changeset.js' {
  declare module.exports: $Exports<'osm-p2p-server/lib/validate_changeset'>;
}
declare module 'osm-p2p-server/routes/changeset_close.js' {
  declare module.exports: $Exports<'osm-p2p-server/routes/changeset_close'>;
}
declare module 'osm-p2p-server/routes/changeset_create.js' {
  declare module.exports: $Exports<'osm-p2p-server/routes/changeset_create'>;
}
declare module 'osm-p2p-server/routes/changeset_download.js' {
  declare module.exports: $Exports<'osm-p2p-server/routes/changeset_download'>;
}
declare module 'osm-p2p-server/routes/changeset_upload.js' {
  declare module.exports: $Exports<'osm-p2p-server/routes/changeset_upload'>;
}
declare module 'osm-p2p-server/routes/changesets.js' {
  declare module.exports: $Exports<'osm-p2p-server/routes/changesets'>;
}
declare module 'osm-p2p-server/routes/element_create.js' {
  declare module.exports: $Exports<'osm-p2p-server/routes/element_create'>;
}
declare module 'osm-p2p-server/routes/element_delete.js' {
  declare module.exports: $Exports<'osm-p2p-server/routes/element_delete'>;
}
declare module 'osm-p2p-server/routes/element_history.js' {
  declare module.exports: $Exports<'osm-p2p-server/routes/element_history'>;
}
declare module 'osm-p2p-server/routes/element_multi_fetch.js' {
  declare module.exports: $Exports<'osm-p2p-server/routes/element_multi_fetch'>;
}
declare module 'osm-p2p-server/routes/element_read.js' {
  declare module.exports: $Exports<'osm-p2p-server/routes/element_read'>;
}
declare module 'osm-p2p-server/routes/element_version.js' {
  declare module.exports: $Exports<'osm-p2p-server/routes/element_version'>;
}
declare module 'osm-p2p-server/routes/index' {
  declare module.exports: $Exports<'osm-p2p-server/routes'>;
}
declare module 'osm-p2p-server/routes/index.js' {
  declare module.exports: $Exports<'osm-p2p-server/routes'>;
}
declare module 'osm-p2p-server/routes/misc_capabilities.js' {
  declare module.exports: $Exports<'osm-p2p-server/routes/misc_capabilities'>;
}
declare module 'osm-p2p-server/routes/misc_map.js' {
  declare module.exports: $Exports<'osm-p2p-server/routes/misc_map'>;
}
declare module 'osm-p2p-server/test/api/close_changeset.test.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/api/close_changeset.test'>;
}
declare module 'osm-p2p-server/test/api/create_changeset.test.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/api/create_changeset.test'>;
}
declare module 'osm-p2p-server/test/api/create_element.test.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/api/create_element.test'>;
}
declare module 'osm-p2p-server/test/api/get_changes.test.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/api/get_changes.test'>;
}
declare module 'osm-p2p-server/test/api/get_element.test.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/api/get_element.test'>;
}
declare module 'osm-p2p-server/test/api/get_map.test.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/api/get_map.test'>;
}
declare module 'osm-p2p-server/test/bbox_order.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/bbox_order'>;
}
declare module 'osm-p2p-server/test/bbox.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/bbox'>;
}
declare module 'osm-p2p-server/test/capabilities.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/capabilities'>;
}
declare module 'osm-p2p-server/test/changeset_delete.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/changeset_delete'>;
}
declare module 'osm-p2p-server/test/changeset_placeholder.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/changeset_placeholder'>;
}
declare module 'osm-p2p-server/test/changeset_upload_observation.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/changeset_upload_observation'>;
}
declare module 'osm-p2p-server/test/changeset_upload_relation.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/changeset_upload_relation'>;
}
declare module 'osm-p2p-server/test/changeset_upload.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/changeset_upload'>;
}
declare module 'osm-p2p-server/test/changeset.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/changeset'>;
}
declare module 'osm-p2p-server/test/delete.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/delete'>;
}
declare module 'osm-p2p-server/test/get_map.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/get_map'>;
}
declare module 'osm-p2p-server/test/ghost_points.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/ghost_points'>;
}
declare module 'osm-p2p-server/test/history.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/history'>;
}
declare module 'osm-p2p-server/test/lib/filter_deletes.test.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/lib/filter_deletes.test'>;
}
declare module 'osm-p2p-server/test/lib/replace_ids.test.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/lib/replace_ids.test'>;
}
declare module 'osm-p2p-server/test/lib/slowdb.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/lib/slowdb'>;
}
declare module 'osm-p2p-server/test/lib/test_db.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/lib/test_db'>;
}
declare module 'osm-p2p-server/test/lib/test_server.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/lib/test_server'>;
}
declare module 'osm-p2p-server/test/lib/util.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/lib/util'>;
}
declare module 'osm-p2p-server/test/lib/validate_changeset.test.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/lib/validate_changeset.test'>;
}
declare module 'osm-p2p-server/test/malformed_changeset.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/malformed_changeset'>;
}
declare module 'osm-p2p-server/test/many_types.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/many_types'>;
}
declare module 'osm-p2p-server/test/multi_fetch.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/multi_fetch'>;
}
declare module 'osm-p2p-server/test/split_delete_way.js' {
  declare module.exports: $Exports<'osm-p2p-server/test/split_delete_way'>;
}
