// flow-typed signature: da52c10d218fa320b8232b39a093905b
// flow-typed version: <<STUB>>/random-access-file_v^2.1.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'random-access-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'random-access-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'random-access-file/browser' {
  declare module.exports: any;
}

declare module 'random-access-file/example' {
  declare module.exports: any;
}

declare module 'random-access-file/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'random-access-file/browser.js' {
  declare module.exports: $Exports<'random-access-file/browser'>;
}
declare module 'random-access-file/example.js' {
  declare module.exports: $Exports<'random-access-file/example'>;
}
declare module 'random-access-file/index' {
  declare module.exports: $Exports<'random-access-file'>;
}
declare module 'random-access-file/index.js' {
  declare module.exports: $Exports<'random-access-file'>;
}
declare module 'random-access-file/test.js' {
  declare module.exports: $Exports<'random-access-file/test'>;
}
