// flow-typed signature: 7f4fd66cb0c40b021aebefcca0ecea6e
// flow-typed version: <<STUB>>/react-storybook-addon-props-combinations_v^1.1.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-storybook-addon-props-combinations'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-storybook-addon-props-combinations' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-storybook-addon-props-combinations/dist/CombinationRenderer' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/dist/ErrorDisplay' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/dist' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/dist/modifiers' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/dist/utils' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/example/basicUsage.story' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/example/combinationsModifier.story' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/example/customCombinationRenderer.story' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/example/mustProvideAllProps.story' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/src/CombinationRenderer' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/src/ErrorDisplay' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/src' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/src/modifiers' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/src/modifiers.test' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/src/utils' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-props-combinations/src/utils.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-storybook-addon-props-combinations/dist/CombinationRenderer.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/dist/CombinationRenderer'>;
}
declare module 'react-storybook-addon-props-combinations/dist/ErrorDisplay.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/dist/ErrorDisplay'>;
}
declare module 'react-storybook-addon-props-combinations/dist/index' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/dist'>;
}
declare module 'react-storybook-addon-props-combinations/dist/index.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/dist'>;
}
declare module 'react-storybook-addon-props-combinations/dist/modifiers.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/dist/modifiers'>;
}
declare module 'react-storybook-addon-props-combinations/dist/utils.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/dist/utils'>;
}
declare module 'react-storybook-addon-props-combinations/example/basicUsage.story.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/example/basicUsage.story'>;
}
declare module 'react-storybook-addon-props-combinations/example/combinationsModifier.story.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/example/combinationsModifier.story'>;
}
declare module 'react-storybook-addon-props-combinations/example/customCombinationRenderer.story.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/example/customCombinationRenderer.story'>;
}
declare module 'react-storybook-addon-props-combinations/example/mustProvideAllProps.story.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/example/mustProvideAllProps.story'>;
}
declare module 'react-storybook-addon-props-combinations/src/CombinationRenderer.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/src/CombinationRenderer'>;
}
declare module 'react-storybook-addon-props-combinations/src/ErrorDisplay.jsx' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/src/ErrorDisplay'>;
}
declare module 'react-storybook-addon-props-combinations/src/index' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/src'>;
}
declare module 'react-storybook-addon-props-combinations/src/index.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/src'>;
}
declare module 'react-storybook-addon-props-combinations/src/modifiers.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/src/modifiers'>;
}
declare module 'react-storybook-addon-props-combinations/src/modifiers.test.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/src/modifiers.test'>;
}
declare module 'react-storybook-addon-props-combinations/src/utils.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/src/utils'>;
}
declare module 'react-storybook-addon-props-combinations/src/utils.test.js' {
  declare module.exports: $Exports<'react-storybook-addon-props-combinations/src/utils.test'>;
}
