// flow-typed signature: b9fe0730eca1ae0712374e263baace51
// flow-typed version: <<STUB>>/react-mapbox-gl_v^4.8.6/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mapbox-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mapbox-gl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-mapbox-gl/lib-esm/cluster' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/context' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/feature' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/geojson-layer' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/image' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/layer-events-hoc' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/layer' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/map-events' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/map' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/marker' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/popup' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/projected-layer' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/rotation-control' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/scale-control' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/source' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/util/classname' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/util/diff' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/util/overlays' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/util/types' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/util/uid' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib-esm/zoom-control' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/cluster' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/context' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/feature' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/geojson-layer' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/image' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/layer-events-hoc' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/layer' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/map-events' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/map' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/marker' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/popup' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/projected-layer' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/rotation-control' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/scale-control' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/source' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/util/classname' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/util/diff' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/util/overlays' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/util/types' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/util/uid' {
  declare module.exports: any;
}

declare module 'react-mapbox-gl/lib/zoom-control' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-mapbox-gl/lib-esm/cluster.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/cluster'>;
}
declare module 'react-mapbox-gl/lib-esm/context.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/context'>;
}
declare module 'react-mapbox-gl/lib-esm/feature.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/feature'>;
}
declare module 'react-mapbox-gl/lib-esm/geojson-layer.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/geojson-layer'>;
}
declare module 'react-mapbox-gl/lib-esm/image.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/image'>;
}
declare module 'react-mapbox-gl/lib-esm/index' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm'>;
}
declare module 'react-mapbox-gl/lib-esm/index.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm'>;
}
declare module 'react-mapbox-gl/lib-esm/layer-events-hoc.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/layer-events-hoc'>;
}
declare module 'react-mapbox-gl/lib-esm/layer.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/layer'>;
}
declare module 'react-mapbox-gl/lib-esm/map-events.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/map-events'>;
}
declare module 'react-mapbox-gl/lib-esm/map.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/map'>;
}
declare module 'react-mapbox-gl/lib-esm/marker.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/marker'>;
}
declare module 'react-mapbox-gl/lib-esm/popup.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/popup'>;
}
declare module 'react-mapbox-gl/lib-esm/projected-layer.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/projected-layer'>;
}
declare module 'react-mapbox-gl/lib-esm/rotation-control.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/rotation-control'>;
}
declare module 'react-mapbox-gl/lib-esm/scale-control.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/scale-control'>;
}
declare module 'react-mapbox-gl/lib-esm/source.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/source'>;
}
declare module 'react-mapbox-gl/lib-esm/util/classname.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/util/classname'>;
}
declare module 'react-mapbox-gl/lib-esm/util/diff.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/util/diff'>;
}
declare module 'react-mapbox-gl/lib-esm/util/overlays.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/util/overlays'>;
}
declare module 'react-mapbox-gl/lib-esm/util/types.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/util/types'>;
}
declare module 'react-mapbox-gl/lib-esm/util/uid.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/util/uid'>;
}
declare module 'react-mapbox-gl/lib-esm/zoom-control.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib-esm/zoom-control'>;
}
declare module 'react-mapbox-gl/lib/cluster.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/cluster'>;
}
declare module 'react-mapbox-gl/lib/context.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/context'>;
}
declare module 'react-mapbox-gl/lib/feature.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/feature'>;
}
declare module 'react-mapbox-gl/lib/geojson-layer.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/geojson-layer'>;
}
declare module 'react-mapbox-gl/lib/image.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/image'>;
}
declare module 'react-mapbox-gl/lib/index' {
  declare module.exports: $Exports<'react-mapbox-gl/lib'>;
}
declare module 'react-mapbox-gl/lib/index.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib'>;
}
declare module 'react-mapbox-gl/lib/layer-events-hoc.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/layer-events-hoc'>;
}
declare module 'react-mapbox-gl/lib/layer.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/layer'>;
}
declare module 'react-mapbox-gl/lib/map-events.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/map-events'>;
}
declare module 'react-mapbox-gl/lib/map.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/map'>;
}
declare module 'react-mapbox-gl/lib/marker.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/marker'>;
}
declare module 'react-mapbox-gl/lib/popup.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/popup'>;
}
declare module 'react-mapbox-gl/lib/projected-layer.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/projected-layer'>;
}
declare module 'react-mapbox-gl/lib/rotation-control.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/rotation-control'>;
}
declare module 'react-mapbox-gl/lib/scale-control.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/scale-control'>;
}
declare module 'react-mapbox-gl/lib/source.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/source'>;
}
declare module 'react-mapbox-gl/lib/util/classname.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/util/classname'>;
}
declare module 'react-mapbox-gl/lib/util/diff.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/util/diff'>;
}
declare module 'react-mapbox-gl/lib/util/overlays.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/util/overlays'>;
}
declare module 'react-mapbox-gl/lib/util/types.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/util/types'>;
}
declare module 'react-mapbox-gl/lib/util/uid.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/util/uid'>;
}
declare module 'react-mapbox-gl/lib/zoom-control.js' {
  declare module.exports: $Exports<'react-mapbox-gl/lib/zoom-control'>;
}
