// flow-typed signature: b1de389ed2a0613c9c49ae3c00ff66ae
// flow-typed version: <<STUB>>/react-error-boundary_v^1.2.5/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-error-boundary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-error-boundary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-error-boundary/dist/commonjs/__tests__/ErrorBoundary.test' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/commonjs/__tests__/ErrorBoundaryFallbackComponent.test' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/commonjs/ErrorBoundary' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/commonjs/ErrorBoundaryFallbackComponent' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/commonjs' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/commonjs/setupTests' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/es/__tests__/ErrorBoundary.test' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/es/__tests__/ErrorBoundaryFallbackComponent.test' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/es/ErrorBoundary' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/es/ErrorBoundaryFallbackComponent' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/es' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/es/setupTests' {
  declare module.exports: any;
}

declare module 'react-error-boundary/dist/umd/react-error-boundary' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-error-boundary/dist/commonjs/__tests__/ErrorBoundary.test.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/commonjs/__tests__/ErrorBoundary.test'>;
}
declare module 'react-error-boundary/dist/commonjs/__tests__/ErrorBoundaryFallbackComponent.test.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/commonjs/__tests__/ErrorBoundaryFallbackComponent.test'>;
}
declare module 'react-error-boundary/dist/commonjs/ErrorBoundary.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/commonjs/ErrorBoundary'>;
}
declare module 'react-error-boundary/dist/commonjs/ErrorBoundaryFallbackComponent.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/commonjs/ErrorBoundaryFallbackComponent'>;
}
declare module 'react-error-boundary/dist/commonjs/index' {
  declare module.exports: $Exports<'react-error-boundary/dist/commonjs'>;
}
declare module 'react-error-boundary/dist/commonjs/index.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/commonjs'>;
}
declare module 'react-error-boundary/dist/commonjs/setupTests.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/commonjs/setupTests'>;
}
declare module 'react-error-boundary/dist/es/__tests__/ErrorBoundary.test.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/es/__tests__/ErrorBoundary.test'>;
}
declare module 'react-error-boundary/dist/es/__tests__/ErrorBoundaryFallbackComponent.test.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/es/__tests__/ErrorBoundaryFallbackComponent.test'>;
}
declare module 'react-error-boundary/dist/es/ErrorBoundary.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/es/ErrorBoundary'>;
}
declare module 'react-error-boundary/dist/es/ErrorBoundaryFallbackComponent.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/es/ErrorBoundaryFallbackComponent'>;
}
declare module 'react-error-boundary/dist/es/index' {
  declare module.exports: $Exports<'react-error-boundary/dist/es'>;
}
declare module 'react-error-boundary/dist/es/index.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/es'>;
}
declare module 'react-error-boundary/dist/es/setupTests.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/es/setupTests'>;
}
declare module 'react-error-boundary/dist/umd/react-error-boundary.js' {
  declare module.exports: $Exports<'react-error-boundary/dist/umd/react-error-boundary'>;
}
