// flow-typed signature: 82406d8bd6625b38522015ab0f1c38e6
// flow-typed version: <<STUB>>/react-intl_v^3.2.4/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intl/dist/components/createFormattedComponent' {
  declare module.exports: any;
}

declare module 'react-intl/dist/components/html-message' {
  declare module.exports: any;
}

declare module 'react-intl/dist/components/injectIntl' {
  declare module.exports: any;
}

declare module 'react-intl/dist/components/message' {
  declare module.exports: any;
}

declare module 'react-intl/dist/components/plural' {
  declare module.exports: any;
}

declare module 'react-intl/dist/components/provider' {
  declare module.exports: any;
}

declare module 'react-intl/dist/components/relative' {
  declare module.exports: any;
}

declare module 'react-intl/dist/components/useIntl' {
  declare module.exports: any;
}

declare module 'react-intl/dist/formatters/dateTime' {
  declare module.exports: any;
}

declare module 'react-intl/dist/formatters/displayName' {
  declare module.exports: any;
}

declare module 'react-intl/dist/formatters/list' {
  declare module.exports: any;
}

declare module 'react-intl/dist/formatters/message' {
  declare module.exports: any;
}

declare module 'react-intl/dist/formatters/number' {
  declare module.exports: any;
}

declare module 'react-intl/dist/formatters/plural' {
  declare module.exports: any;
}

declare module 'react-intl/dist/formatters/relativeTime' {
  declare module.exports: any;
}

declare module 'react-intl/dist' {
  declare module.exports: any;
}

declare module 'react-intl/dist/react-intl' {
  declare module.exports: any;
}

declare module 'react-intl/dist/react-intl.min' {
  declare module.exports: any;
}

declare module 'react-intl/dist/types' {
  declare module.exports: any;
}

declare module 'react-intl/dist/utils' {
  declare module.exports: any;
}

declare module 'react-intl/lib/components/createFormattedComponent' {
  declare module.exports: any;
}

declare module 'react-intl/lib/components/html-message' {
  declare module.exports: any;
}

declare module 'react-intl/lib/components/injectIntl' {
  declare module.exports: any;
}

declare module 'react-intl/lib/components/message' {
  declare module.exports: any;
}

declare module 'react-intl/lib/components/plural' {
  declare module.exports: any;
}

declare module 'react-intl/lib/components/provider' {
  declare module.exports: any;
}

declare module 'react-intl/lib/components/relative' {
  declare module.exports: any;
}

declare module 'react-intl/lib/components/useIntl' {
  declare module.exports: any;
}

declare module 'react-intl/lib/formatters/dateTime' {
  declare module.exports: any;
}

declare module 'react-intl/lib/formatters/displayName' {
  declare module.exports: any;
}

declare module 'react-intl/lib/formatters/list' {
  declare module.exports: any;
}

declare module 'react-intl/lib/formatters/message' {
  declare module.exports: any;
}

declare module 'react-intl/lib/formatters/number' {
  declare module.exports: any;
}

declare module 'react-intl/lib/formatters/plural' {
  declare module.exports: any;
}

declare module 'react-intl/lib/formatters/relativeTime' {
  declare module.exports: any;
}

declare module 'react-intl/lib' {
  declare module.exports: any;
}

declare module 'react-intl/lib/types' {
  declare module.exports: any;
}

declare module 'react-intl/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intl/dist/components/createFormattedComponent.js' {
  declare module.exports: $Exports<'react-intl/dist/components/createFormattedComponent'>;
}
declare module 'react-intl/dist/components/html-message.js' {
  declare module.exports: $Exports<'react-intl/dist/components/html-message'>;
}
declare module 'react-intl/dist/components/injectIntl.js' {
  declare module.exports: $Exports<'react-intl/dist/components/injectIntl'>;
}
declare module 'react-intl/dist/components/message.js' {
  declare module.exports: $Exports<'react-intl/dist/components/message'>;
}
declare module 'react-intl/dist/components/plural.js' {
  declare module.exports: $Exports<'react-intl/dist/components/plural'>;
}
declare module 'react-intl/dist/components/provider.js' {
  declare module.exports: $Exports<'react-intl/dist/components/provider'>;
}
declare module 'react-intl/dist/components/relative.js' {
  declare module.exports: $Exports<'react-intl/dist/components/relative'>;
}
declare module 'react-intl/dist/components/useIntl.js' {
  declare module.exports: $Exports<'react-intl/dist/components/useIntl'>;
}
declare module 'react-intl/dist/formatters/dateTime.js' {
  declare module.exports: $Exports<'react-intl/dist/formatters/dateTime'>;
}
declare module 'react-intl/dist/formatters/displayName.js' {
  declare module.exports: $Exports<'react-intl/dist/formatters/displayName'>;
}
declare module 'react-intl/dist/formatters/list.js' {
  declare module.exports: $Exports<'react-intl/dist/formatters/list'>;
}
declare module 'react-intl/dist/formatters/message.js' {
  declare module.exports: $Exports<'react-intl/dist/formatters/message'>;
}
declare module 'react-intl/dist/formatters/number.js' {
  declare module.exports: $Exports<'react-intl/dist/formatters/number'>;
}
declare module 'react-intl/dist/formatters/plural.js' {
  declare module.exports: $Exports<'react-intl/dist/formatters/plural'>;
}
declare module 'react-intl/dist/formatters/relativeTime.js' {
  declare module.exports: $Exports<'react-intl/dist/formatters/relativeTime'>;
}
declare module 'react-intl/dist/index' {
  declare module.exports: $Exports<'react-intl/dist'>;
}
declare module 'react-intl/dist/index.js' {
  declare module.exports: $Exports<'react-intl/dist'>;
}
declare module 'react-intl/dist/react-intl.js' {
  declare module.exports: $Exports<'react-intl/dist/react-intl'>;
}
declare module 'react-intl/dist/react-intl.min.js' {
  declare module.exports: $Exports<'react-intl/dist/react-intl.min'>;
}
declare module 'react-intl/dist/types.js' {
  declare module.exports: $Exports<'react-intl/dist/types'>;
}
declare module 'react-intl/dist/utils.js' {
  declare module.exports: $Exports<'react-intl/dist/utils'>;
}
declare module 'react-intl/lib/components/createFormattedComponent.js' {
  declare module.exports: $Exports<'react-intl/lib/components/createFormattedComponent'>;
}
declare module 'react-intl/lib/components/html-message.js' {
  declare module.exports: $Exports<'react-intl/lib/components/html-message'>;
}
declare module 'react-intl/lib/components/injectIntl.js' {
  declare module.exports: $Exports<'react-intl/lib/components/injectIntl'>;
}
declare module 'react-intl/lib/components/message.js' {
  declare module.exports: $Exports<'react-intl/lib/components/message'>;
}
declare module 'react-intl/lib/components/plural.js' {
  declare module.exports: $Exports<'react-intl/lib/components/plural'>;
}
declare module 'react-intl/lib/components/provider.js' {
  declare module.exports: $Exports<'react-intl/lib/components/provider'>;
}
declare module 'react-intl/lib/components/relative.js' {
  declare module.exports: $Exports<'react-intl/lib/components/relative'>;
}
declare module 'react-intl/lib/components/useIntl.js' {
  declare module.exports: $Exports<'react-intl/lib/components/useIntl'>;
}
declare module 'react-intl/lib/formatters/dateTime.js' {
  declare module.exports: $Exports<'react-intl/lib/formatters/dateTime'>;
}
declare module 'react-intl/lib/formatters/displayName.js' {
  declare module.exports: $Exports<'react-intl/lib/formatters/displayName'>;
}
declare module 'react-intl/lib/formatters/list.js' {
  declare module.exports: $Exports<'react-intl/lib/formatters/list'>;
}
declare module 'react-intl/lib/formatters/message.js' {
  declare module.exports: $Exports<'react-intl/lib/formatters/message'>;
}
declare module 'react-intl/lib/formatters/number.js' {
  declare module.exports: $Exports<'react-intl/lib/formatters/number'>;
}
declare module 'react-intl/lib/formatters/plural.js' {
  declare module.exports: $Exports<'react-intl/lib/formatters/plural'>;
}
declare module 'react-intl/lib/formatters/relativeTime.js' {
  declare module.exports: $Exports<'react-intl/lib/formatters/relativeTime'>;
}
declare module 'react-intl/lib/index' {
  declare module.exports: $Exports<'react-intl/lib'>;
}
declare module 'react-intl/lib/index.js' {
  declare module.exports: $Exports<'react-intl/lib'>;
}
declare module 'react-intl/lib/types.js' {
  declare module.exports: $Exports<'react-intl/lib/types'>;
}
declare module 'react-intl/lib/utils.js' {
  declare module.exports: $Exports<'react-intl/lib/utils'>;
}
