// flow-typed signature: 7ce944f7cb16cfe592353e057023a6fe
// flow-typed version: <<STUB>>/react-image_v^2.4.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-image/cjs' {
  declare module.exports: any;
}

declare module 'react-image/cjs/index.ssr-test' {
  declare module.exports: any;
}

declare module 'react-image/cjs/index.test' {
  declare module.exports: any;
}

declare module 'react-image/umd' {
  declare module.exports: any;
}

declare module 'react-image/umd/index.ssr-test' {
  declare module.exports: any;
}

declare module 'react-image/umd/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-image/cjs/index' {
  declare module.exports: $Exports<'react-image/cjs'>;
}
declare module 'react-image/cjs/index.js' {
  declare module.exports: $Exports<'react-image/cjs'>;
}
declare module 'react-image/cjs/index.ssr-test.js' {
  declare module.exports: $Exports<'react-image/cjs/index.ssr-test'>;
}
declare module 'react-image/cjs/index.test.js' {
  declare module.exports: $Exports<'react-image/cjs/index.test'>;
}
declare module 'react-image/umd/index' {
  declare module.exports: $Exports<'react-image/umd'>;
}
declare module 'react-image/umd/index.js' {
  declare module.exports: $Exports<'react-image/umd'>;
}
declare module 'react-image/umd/index.ssr-test.js' {
  declare module.exports: $Exports<'react-image/umd/index.ssr-test'>;
}
declare module 'react-image/umd/index.test.js' {
  declare module.exports: $Exports<'react-image/umd/index.test'>;
}
