// flow-typed signature: 0e7ae2f4cf574f18cb2b76410d63cd85
// flow-typed version: <<STUB>>/run-series_v^1.1.4/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'run-series'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'run-series' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'run-series/index' {
  declare module.exports: $Exports<'run-series'>;
}
declare module 'run-series/index.js' {
  declare module.exports: $Exports<'run-series'>;
}
