// flow-typed signature: 6530007f6f36be0d2aaa170ffaffceca
// flow-typed version: <<STUB>>/run-parallel-limit_v^1.0.5/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'run-parallel-limit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'run-parallel-limit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'run-parallel-limit/index' {
  declare module.exports: $Exports<'run-parallel-limit'>;
}
declare module 'run-parallel-limit/index.js' {
  declare module.exports: $Exports<'run-parallel-limit'>;
}
