// flow-typed signature: 1f090fa98f8fc8d27d8dc4442b89d433
// flow-typed version: <<STUB>>/safe-fs-blob-store_v^1.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'safe-fs-blob-store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'safe-fs-blob-store' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'safe-fs-blob-store/ex' {
  declare module.exports: any;
}

declare module 'safe-fs-blob-store/test/atomic' {
  declare module.exports: any;
}

declare module 'safe-fs-blob-store/test/common' {
  declare module.exports: any;
}

declare module 'safe-fs-blob-store/test/list' {
  declare module.exports: any;
}

declare module 'safe-fs-blob-store/test/read-write' {
  declare module.exports: any;
}

declare module 'safe-fs-blob-store/test/windows' {
  declare module.exports: any;
}

// Filename aliases
declare module 'safe-fs-blob-store/ex.js' {
  declare module.exports: $Exports<'safe-fs-blob-store/ex'>;
}
declare module 'safe-fs-blob-store/index' {
  declare module.exports: $Exports<'safe-fs-blob-store'>;
}
declare module 'safe-fs-blob-store/index.js' {
  declare module.exports: $Exports<'safe-fs-blob-store'>;
}
declare module 'safe-fs-blob-store/test/atomic.js' {
  declare module.exports: $Exports<'safe-fs-blob-store/test/atomic'>;
}
declare module 'safe-fs-blob-store/test/common.js' {
  declare module.exports: $Exports<'safe-fs-blob-store/test/common'>;
}
declare module 'safe-fs-blob-store/test/list.js' {
  declare module.exports: $Exports<'safe-fs-blob-store/test/list'>;
}
declare module 'safe-fs-blob-store/test/read-write.js' {
  declare module.exports: $Exports<'safe-fs-blob-store/test/read-write'>;
}
declare module 'safe-fs-blob-store/test/windows.js' {
  declare module.exports: $Exports<'safe-fs-blob-store/test/windows'>;
}
