// flow-typed signature: 2a3d7bccf491ea7acfdf51147d247c83
// flow-typed version: <<STUB>>/signal-exit_v^3.0.3/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'signal-exit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'signal-exit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'signal-exit/signals' {
  declare module.exports: any;
}

// Filename aliases
declare module 'signal-exit/index' {
  declare module.exports: $Exports<'signal-exit'>;
}
declare module 'signal-exit/index.js' {
  declare module.exports: $Exports<'signal-exit'>;
}
declare module 'signal-exit/signals.js' {
  declare module.exports: $Exports<'signal-exit/signals'>;
}
