// flow-typed signature: de55b9004b712e59d76c7c8de29205eb
// flow-typed version: <<STUB>>/storybook-addon-i18n_v^5.1.11/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-i18n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-i18n' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-addon-i18n/dist' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n/dist/LocaleSelector' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n/dist/Provider' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n/dist/register' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n/dist/shared' {
  declare module.exports: any;
}

declare module 'storybook-addon-i18n/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-addon-i18n/dist/index' {
  declare module.exports: $Exports<'storybook-addon-i18n/dist'>;
}
declare module 'storybook-addon-i18n/dist/index.js' {
  declare module.exports: $Exports<'storybook-addon-i18n/dist'>;
}
declare module 'storybook-addon-i18n/dist/LocaleSelector.js' {
  declare module.exports: $Exports<'storybook-addon-i18n/dist/LocaleSelector'>;
}
declare module 'storybook-addon-i18n/dist/Provider.js' {
  declare module.exports: $Exports<'storybook-addon-i18n/dist/Provider'>;
}
declare module 'storybook-addon-i18n/dist/register.js' {
  declare module.exports: $Exports<'storybook-addon-i18n/dist/register'>;
}
declare module 'storybook-addon-i18n/dist/shared.js' {
  declare module.exports: $Exports<'storybook-addon-i18n/dist/shared'>;
}
declare module 'storybook-addon-i18n/register.js' {
  declare module.exports: $Exports<'storybook-addon-i18n/register'>;
}
