// flow-typed signature: aac128e5855dc4b11e7c59fd613aa7a8
// flow-typed version: <<STUB>>/subleveldown_v^3.0.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'subleveldown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'subleveldown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'subleveldown/example' {
  declare module.exports: any;
}

declare module 'subleveldown/leveldown' {
  declare module.exports: any;
}

declare module 'subleveldown/test/common' {
  declare module.exports: any;
}

declare module 'subleveldown/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'subleveldown/example.js' {
  declare module.exports: $Exports<'subleveldown/example'>;
}
declare module 'subleveldown/index' {
  declare module.exports: $Exports<'subleveldown'>;
}
declare module 'subleveldown/index.js' {
  declare module.exports: $Exports<'subleveldown'>;
}
declare module 'subleveldown/leveldown.js' {
  declare module.exports: $Exports<'subleveldown/leveldown'>;
}
declare module 'subleveldown/test/common.js' {
  declare module.exports: $Exports<'subleveldown/test/common'>;
}
declare module 'subleveldown/test/index' {
  declare module.exports: $Exports<'subleveldown/test'>;
}
declare module 'subleveldown/test/index.js' {
  declare module.exports: $Exports<'subleveldown/test'>;
}
