// flow-typed signature: 6dd0f8f2e93aac5e69fe354ef5a7ceb1
// flow-typed version: <<STUB>>/tar-fs_v^1.16.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tar-fs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tar-fs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tar-fs/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tar-fs/index' {
  declare module.exports: $Exports<'tar-fs'>;
}
declare module 'tar-fs/index.js' {
  declare module.exports: $Exports<'tar-fs'>;
}
declare module 'tar-fs/test/index' {
  declare module.exports: $Exports<'tar-fs/test'>;
}
declare module 'tar-fs/test/index.js' {
  declare module.exports: $Exports<'tar-fs/test'>;
}
