// flow-typed signature: 4a870faecfbb46f818a9402228670022
// flow-typed version: <<STUB>>/terminate_v^2.1.2/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'terminate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'terminate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'terminate/handlePsTreeCallback' {
  declare module.exports: any;
}

declare module 'terminate/terminate' {
  declare module.exports: any;
}

declare module 'terminate/test/exec/child' {
  declare module.exports: any;
}

declare module 'terminate/test/exec/parent' {
  declare module.exports: any;
}

declare module 'terminate/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'terminate/handlePsTreeCallback.js' {
  declare module.exports: $Exports<'terminate/handlePsTreeCallback'>;
}
declare module 'terminate/terminate.js' {
  declare module.exports: $Exports<'terminate/terminate'>;
}
declare module 'terminate/test/exec/child.js' {
  declare module.exports: $Exports<'terminate/test/exec/child'>;
}
declare module 'terminate/test/exec/parent.js' {
  declare module.exports: $Exports<'terminate/test/exec/parent'>;
}
declare module 'terminate/test/test.js' {
  declare module.exports: $Exports<'terminate/test/test'>;
}
