// flow-typed signature: 3a38999c5a4e8cac747ac63cfe49cb5b
// flow-typed version: <<STUB>>/utm_v^1.1.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'utm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'utm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'utm/index.es' {
  declare module.exports: any;
}

declare module 'utm/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'utm/index.es.js' {
  declare module.exports: $Exports<'utm/index.es'>;
}
declare module 'utm/index' {
  declare module.exports: $Exports<'utm'>;
}
declare module 'utm/index.js' {
  declare module.exports: $Exports<'utm'>;
}
declare module 'utm/test.js' {
  declare module.exports: $Exports<'utm/test'>;
}
