// flow-typed signature: b9901d2eb50363b6b3f65fe84df89ee1
// flow-typed version: <<STUB>>/@bugsnag/browser_v^7.1.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@bugsnag/browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@bugsnag/browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@bugsnag/browser/dist/bugsnag' {
  declare module.exports: any;
}

declare module '@bugsnag/browser/dist/bugsnag.min' {
  declare module.exports: any;
}

declare module '@bugsnag/browser/types/test/types.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@bugsnag/browser/dist/bugsnag.js' {
  declare module.exports: $Exports<'@bugsnag/browser/dist/bugsnag'>;
}
declare module '@bugsnag/browser/dist/bugsnag.min.js' {
  declare module.exports: $Exports<'@bugsnag/browser/dist/bugsnag.min'>;
}
declare module '@bugsnag/browser/types/test/types.test.js' {
  declare module.exports: $Exports<'@bugsnag/browser/types/test/types.test'>;
}
