// flow-typed signature: e8210aa3682821c66ab3cce8ac8a6c64
// flow-typed version: <<STUB>>/@bugsnag/js_v^7.1.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@bugsnag/js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@bugsnag/js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@bugsnag/js/browser/notifier' {
  declare module.exports: any;
}

declare module '@bugsnag/js/node/notifier' {
  declare module.exports: any;
}

// Filename aliases
declare module '@bugsnag/js/browser/notifier.js' {
  declare module.exports: $Exports<'@bugsnag/js/browser/notifier'>;
}
declare module '@bugsnag/js/node/notifier.js' {
  declare module.exports: $Exports<'@bugsnag/js/node/notifier'>;
}
