// flow-typed signature: 5244993261d7f9861ea17f4c094cba37
// flow-typed version: <<STUB>>/@mapbox/sexagesimal_v^1.2.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/sexagesimal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/sexagesimal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mapbox/sexagesimal/sexagesimal' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mapbox/sexagesimal/index' {
  declare module.exports: $Exports<'@mapbox/sexagesimal'>;
}
declare module '@mapbox/sexagesimal/index.js' {
  declare module.exports: $Exports<'@mapbox/sexagesimal'>;
}
declare module '@mapbox/sexagesimal/sexagesimal.js' {
  declare module.exports: $Exports<'@mapbox/sexagesimal/sexagesimal'>;
}
