// flow-typed signature: b839c6f9fe21d34cb4a51e094ce5c2a1
// flow-typed version: <<STUB>>/@segment/isodate_v^1.0.3/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@segment/isodate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@segment/isodate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@segment/isodate/karma.conf.ci' {
  declare module.exports: any;
}

declare module '@segment/isodate/karma.conf' {
  declare module.exports: any;
}

declare module '@segment/isodate/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@segment/isodate/karma.conf.ci.js' {
  declare module.exports: $Exports<'@segment/isodate/karma.conf.ci'>;
}
declare module '@segment/isodate/karma.conf.js' {
  declare module.exports: $Exports<'@segment/isodate/karma.conf'>;
}
declare module '@segment/isodate/lib/index' {
  declare module.exports: $Exports<'@segment/isodate/lib'>;
}
declare module '@segment/isodate/lib/index.js' {
  declare module.exports: $Exports<'@segment/isodate/lib'>;
}
