export const TEXT = 'text'
export const TEXTAREA = 'textarea'
export const NUMBER = 'number'
export const SELECT_ONE = 'select_one'
export const SELECT_MULTIPLE = 'select_multiple'
export const DATE = 'date'
export const DATETIME = 'datetime'
export const LINK = 'link'
