// flow-typed signature: e965417fe8afb70334a189cf48a73121
// flow-typed version: <<STUB>>/@digidem/extract-react-intl-messages_v^2.0.2/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@digidem/extract-react-intl-messages'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@digidem/extract-react-intl-messages' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@digidem/extract-react-intl-messages/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module '@digidem/extract-react-intl-messages/cli.js' {
  declare module.exports: $Exports<'@digidem/extract-react-intl-messages/cli'>;
}
declare module '@digidem/extract-react-intl-messages/index' {
  declare module.exports: $Exports<'@digidem/extract-react-intl-messages'>;
}
declare module '@digidem/extract-react-intl-messages/index.js' {
  declare module.exports: $Exports<'@digidem/extract-react-intl-messages'>;
}
