// flow-typed signature: 9eedbeb35f5918e80566046feb1626d8
// flow-typed version: <<STUB>>/@mapeo/settings_v^2.1.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapeo/settings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapeo/settings' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@mapeo/settings/index' {
  declare module.exports: $Exports<'@mapeo/settings'>;
}
declare module '@mapeo/settings/index.js' {
  declare module.exports: $Exports<'@mapeo/settings'>;
}
